Feat: XML Upload (upload to blob by uniqueString)
alphayesodot/itur-be-functionapp pull request #1
Opened 2021-02-02 20:49 UTC by AdarPascal

2021-02-04 22:44 UTC, ShragaUser requested changes

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/function.json
> +      "name": "PsifasBlob",
Should be psiphas

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/config.ts
> +        blobName: findObjInArrByKey(functionConf.bindings, 'name', 'Haman').name,
Shouldn't this be HamanBlob?

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/config.ts
> +        uniqueString: env.get('Haman_XML_Unique_String').required().asString()
Environment variables should be all CAPS

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/function.json
> +        "get",
Is get needed?

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/index.ts
> +        if (validate(req.body) !== true) throw new HttpFunctionAppError(400, 'XML structure incorrect');
File content is in req.body?
Shouldn't this be a data stream of the file?

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/index.ts
> +        config.blobsFilterConf.forEach(blobFilter => blobUploadByFileType(blobFilter.blobName, blobFilter.uniqueString));
Can there actually be more than one xml type in a given call to the api?
If so - than why go over every "filterConf" instead of only invoking the relevant function handler?

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/index.ts
> +        return context.done();
Async functions don't require context.done.
It is implicitly called on return

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/utils/find.ts
> +    return arr.find((obj: any) => obj[key].toLowerCase().includes(value.toLowerCase()));
Would change to "ByKeyValue"

2021-02-04 22:44 UTC, ShragaUser commented on xml-upload/utils/find.ts
> +    return arr.find((obj: any) => obj[key].toLowerCase().includes(value.toLowerCase()));
Should this be includes and not equals?

2021-02-04 22:48 UTC, AdarPascal commented on xml-upload/config.ts
> +        uniqueString: env.get('Haman_XML_Unique_String').required().asString()
Already done. Will be updated with the next commit to come out

2021-02-04 22:50 UTC, AdarPascal commented on xml-upload/function.json
> +        "get",
Fixing

2021-02-04 22:52 UTC, AdarPascal commented on xml-upload/config.ts
> +        blobName: findObjInArrByKey(functionConf.bindings, 'name', 'Haman').name,
No, the `findObjInArrByKey` Function searching for a blob name in the bindings section that includes the string Haman in it.
U can see the function definition in ./utils/find.ts

2021-02-04 23:03 UTC, AdarPascal commented on xml-upload/index.ts
> +        if (validate(req.body) !== true) throw new HttpFunctionAppError(400, 'XML structure incorrect');
After a lot of research and failed attempts to read a file from multipart-form-data like used in 99% cases of file upload, then using the Multer Express middleware to parse and save the file, I've couldn't manage to read a file from an http request in azure function as I've done before with express.
In the spec of performance, I've got 0.8 sec for 1 MB upload speed (The test ran on a 20 MB/s upload speed internet connection), while in our internet version of Dropbox, that uses Multer and multipart, it takes 0.5 sec for 1 MB upload.

Discussed this with @yubbi99, she said that for the current sprint she is ok with this.
It's ok right ? (@yubbi99 @ShragaUser)

2021-02-04 23:07 UTC, AdarPascal commented on xml-upload/index.ts
> +        config.blobsFilterConf.forEach(blobFilter => blobUploadByFileType(blobFilter.blobName, blobFilter.uniqueString));
For that I wrote `return context.done();` in line 19.
If the file type was found and handled, the function's code runtime will be over.

2021-02-04 23:08 UTC, AdarPascal commented on xml-upload/utils/find.ts
> +    return arr.find((obj: any) => obj[key].toLowerCase().includes(value.toLowerCase()));
Correcting

2021-02-04 23:10 UTC, AdarPascal commented on xml-upload/utils/find.ts
> +    return arr.find((obj: any) => obj[key].toLowerCase().includes(value.toLowerCase()));
No, I'm trying to יelp the following maintainers of the code.
If the config will have some mistakes, this code should help them get over those mistakes.

2021-02-04 23:12 UTC, ShragaUser commented on xml-upload/config.ts
> +        blobName: findObjInArrByKey(functionConf.bindings, 'name', 'Haman').name,
This isn't super obvious given the function name. 
Also than maybe consider removing 'blob' from the other 2 configurations?

2021-02-04 23:15 UTC, ShragaUser commented on xml-upload/index.ts
> +        config.blobsFilterConf.forEach(blobFilter => blobUploadByFileType(blobFilter.blobName, blobFilter.uniqueString));
return inside of a forEach block doesn't stop the iteration and execution of the next items in the loop.
Though using context.done() probably does this - are we sure that no code runs after "done" is called?

2021-02-04 23:17 UTC, ShragaUser commented on xml-upload/utils/find.ts
> +    return arr.find((obj: any) => obj[key].toLowerCase().includes(value.toLowerCase()));
Could also lead to mistakes, if maybe 2 different params have the same prefix. 

This isn't a bad behavior but I would add this as a comment or maybe add this to function name

2021-02-04 23:19 UTC, ShragaUser commented on xml-upload/index.ts
> +        if (validate(req.body) !== true) throw new HttpFunctionAppError(400, 'XML structure incorrect');
If this is a temporary solution ( which is somewhat ok ) than that should be obvious in code using comments. 

This should also be followed by an issue to resolve going forward. 

We'll have to address this sooner or later anyway, considering we have a lot of uploads and downloads going forward.

2021-02-04 23:22 UTC, AdarPascal commented on xml-upload/config.ts
> +        blobName: findObjInArrByKey(functionConf.bindings, 'name', 'Haman').name,
Right, it's not really clear.
Changing the function name and the other 'blob' string parts.

2021-02-04 23:24 UTC, AdarPascal commented on xml-upload/function.json
> +      "name": "PsifasBlob",
Correcting

2021-02-04 23:45 UTC, AdarPascal commented on xml-upload/index.ts
> +        config.blobsFilterConf.forEach(blobFilter => blobUploadByFileType(blobFilter.blobName, blobFilter.uniqueString));
You're right about the return part, I will correct it.

According to Microsoft Documentation, the context.done( ) function > Lets the runtime know that your code has completed.

I can't really understand if no code runs after "done" is called because of this very limited explanation of the function by Microsoft, but if in the worst case some code still runs we shouldn't care about it cause it won't interrupt the function run or out bindings that called by this function.

2021-02-04 23:47 UTC, AdarPascal commented on xml-upload/config.ts
> +        blobName: findObjInArrByKey(functionConf.bindings, 'name', 'Haman').name,
I can use 'every' function on the array, but it won't be clean.
What do you think about it ?

2021-02-04 23:48 UTC, AdarPascal commented on xml-upload/index.ts
> +        return context.done();
Correcting

2021-02-04 23:52 UTC, AdarPascal commented on xml-upload/utils/find.ts
> +    return arr.find((obj: any) => obj[key].toLowerCase().includes(value.toLowerCase()));
If I was checking if equals, then every blob container name config change would be in 2 parts of the code.
This function is for saving that.

Changing the function name for it to be clear.

2021-02-05 08:27 UTC, ShragaUser commented on xml-upload/config.ts
> +        blobName: findObjInArrByKey(functionConf.bindings, 'name', 'Haman').name,
No, I think the current implementation is great, no need to change 👍

2021-02-08 15:24 UTC, ShragaUser submitted a review, later dismissed
LGTM

2021-02-10 11:02 UTC, yonatandt commented
@AdarPascal why did you close the PR?
Didn't you want to merge it?

2021-02-16 14:58 UTC, lustigy96 commented on xml-upload/index.ts
> +const httpTrigger: AzureFunction = async (context: Context, req: HttpRequest): Promise<void> => {
use a better name for this function

2021-06-30 11:08 UTC, closed without merging