Function/malshab update
alphayesodot/itur-be-functionapp pull request #12
Opened 2021-02-09 13:53 UTC by yonatandt

Still need to test against malshab-tests update.

2021-02-10 22:05 UTC, lustigy96 requested changes

2021-04-06 08:18 UTC, yonatandt commented on UpdateMalshab/index.ts
> +            throw new Error('The malshabUpdate message arrived as string instead of a JSON object, the object is probably invalid.');
You can read about it [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=csharp):
> When a queue trigger function fails, Azure Functions retries the function up to five times for a given queue message, including the first try. If all five attempts fail, the functions runtime adds a message to a queue named <originalqueuename>-poison. You can write a function to process messages from the poison queue by logging them or sending a notification that manual attention is needed.

2021-04-06 09:47 UTC, carmeltsadok approved these changes

2021-04-07 08:27 UTC, lustigy96 approved these changes

2021-04-11 06:51 UTC, merged