Time trigger
alphayesodot/itur-be-functionapp pull request #122
Opened 2021-08-09 12:50 UTC by maykremer

2021-08-09 12:52 UTC, carmeltsadok submitted a review, later dismissed

2021-08-10 08:48 UTC, lustigy96 requested changes

2021-08-10 08:48 UTC, lustigy96 commented on shared/queue/queue.tools.ts
> +    } catch (e) {
This is not a good check since parse will work on array too ... (I don't know if it is a critical case, but consider it)

2021-08-10 10:34 UTC, lustigy96 approved these changes

2021-08-10 10:35 UTC, carmeltsadok approved these changes

2021-08-10 10:36 UTC, merged