new function app - deleteNode
alphayesodot/itur-be-functionapp pull request #125
Opened 2021-08-10 11:22 UTC by lihi2910

add deleteNode function app

2021-08-10 11:51 UTC, maykremer requested changes

2021-08-10 11:51 UTC, maykremer commented on CreateEvent/validation.ts
> +
```suggestion
```

2021-08-10 11:51 UTC, maykremer commented on DeleteNode/index.ts
> +        console.log(nodeToDelete.nodeGroupId);
```suggestion
```

2021-08-10 11:51 UTC, maykremer commented on DeleteNode/index.ts
> +            console.log('not possible');
```suggestion
```

2021-08-10 11:51 UTC, maykremer commented on DeleteNode/index.ts
> +        console.log(nodeToDelete);
```suggestion
```

2021-08-10 11:51 UTC, maykremer commented on DeleteNode/index.ts
> +            console.log('not delete');
```suggestion
```

2021-08-10 11:51 UTC, maykremer commented on DeleteNode/index.ts
> +        const deletedNode: Node = await NodeModel.findByIdAndDelete(nodeToDelete);
You need to do `findOne` because the objectId is different than the `id` parameter

2021-08-10 11:51 UTC, maykremer commented on DeleteNode/index.ts
> +        console.log(httpErrorHandler(error, functionName));
```suggestion
```

2021-08-10 11:51 UTC, maykremer commented on shared/node/node.model.ts
> +            // default: NodeType.Unknown,
why?

2021-08-10 14:43 UTC, lihi2910 commented on DeleteNode/index.ts
> +        const deletedNode: Node = await NodeModel.findByIdAndDelete(nodeToDelete);
nodeToDelete include the objectId, I got it from the db

2021-08-11 08:50 UTC, carmeltsadok approved these changes

2021-08-12 06:41 UTC, carmeltsadok requested changes

2021-08-12 06:41 UTC, carmeltsadok commented on DeleteNode/index.ts
> +import NodeGroupModel from '../shared/nodeGroup/nodeGroup.model';
```suggestion
```

2021-08-12 11:20 UTC, carmeltsadok submitted a review, later dismissed

2021-08-15 12:48 UTC, lustigy96 requested changes

2021-08-15 12:48 UTC, lustigy96 commented on DeleteNode/index.ts
> +        if (nodeToDelete.nodeGroupId) {
```suggestion
        // check if node not connected to NodeGroup
        if (nodeToDelete.nodeGroupId) {
```

2021-08-15 12:48 UTC, lustigy96 commented on DeleteNode/index.ts
> +        // check if node not connected to NodeGroup
```suggestion
```

2021-08-15 12:48 UTC, lustigy96 commented on DeleteNode/index.ts
> +
choose between to tow conditions of the deletedNode

2021-08-15 13:47 UTC, lustigy96 approved these changes

2021-08-15 14:11 UTC, merged