feature/azure-sas-token
alphayesodot/itur-be-functionapp pull request #128
Opened 2021-08-12 11:58 UTC by PCOffline

Change the preparation kit files functions to a function that returns SAS tokens to the files in the blob storage

2021-08-12 12:06 UTC, Delitefully approved these changes

2021-08-12 14:04 UTC, Delitefully approved these changes

2021-08-12 14:27 UTC, Delitefully submitted a review, later dismissed

2021-08-15 07:40 UTC, carmeltsadok requested changes

2021-08-15 07:40 UTC, carmeltsadok commented on GetPreparationKitSas/index.ts
> +const GetPreparationKitSas: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
why this function exist

2021-08-15 08:09 UTC, PCOffline commented on GetPreparationKitSas/index.ts
> +const GetPreparationKitSas: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
It's a faster way to pull the video:
Instead of downloading it, I simply provide a URL to that gives access to the video in the blob storage. That way, it simply loads the hosted video from the URL instead of downloading the actual file.

2021-08-15 08:56 UTC, carmeltsadok commented on GetPreparationKitSas/index.ts
> +const GetPreparationKitSas: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
but why 2 functions? and not changing the first one

2021-08-15 09:05 UTC, PCOffline commented on GetPreparationKitSas/index.ts
> +const GetPreparationKitSas: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
This method does not work with the PDF due to CORS, that I didn't manage to solve.

2021-08-15 12:13 UTC, PCOffline commented
Compatible with https://github.com/alphayesodot/itur-client/pull/122

2021-08-15 13:36 UTC, lustigy96 requested changes

2021-08-15 13:36 UTC, lustigy96 commented on config.ts
> +        videoSas: env.get('PREPARATION_KIT_VIDEO_SAS').required().asUrlString(),
write a default value

2021-08-16 12:17 UTC, carmeltsadok submitted a review, later dismissed

2021-08-16 16:27 UTC, PCOffline commented on GetPreparationKitSas/index.ts
> +const GetPreparationKitSas: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
Can't be solved right now.

2021-08-16 16:27 UTC, PCOffline commented on config.ts
> +        videoSas: env.get('PREPARATION_KIT_VIDEO_SAS').required().asUrlString(),
Done!

2021-08-17 11:13 UTC, carmeltsadok approved these changes

2021-08-17 11:13 UTC, carmeltsadok commented on GetPreparationKitSas/index.ts
> +const GetPreparationKitSas: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
add a comment in here like you wrote in the mock server in the  client, explaining what is sas

2021-08-17 11:39 UTC, carmeltsadok approved these changes

2021-08-17 11:40 UTC, merged