Get malshab
alphayesodot/itur-be-functionapp pull request #13
Opened 2021-02-10 15:01 UTC by lustigy96

2021-02-10 15:48 UTC, yonatandt requested changes

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/function.json
> +  "scriptFile": "../dist/getMalshab/index.js"
According to the naming conventions we have (in the Trello), function names should be in PascalCase.

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +  await mongoose.connect("mongodb://"+ process.env.COSMOSDB_HOST+":"+process.env.COSMOSDB_PORT+"/"+process.env.COSMOSDB_DBNAME+"?ssl=true&replicaSet=globaldb&retryWrites=false", {
This will create a mongoose client on each function invocation, which is not advised.
See https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections.
Also, @vitaly-furman shared a medium post about it in Discord, which gives an example of what you should do.

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +const httpTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
Should give a more meaningful name to the function.

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +    name: req.query.name || (req.body && req.body.name)
I think there should be one specific predefined place for each of the inputs.

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +    name: req.query.name || (req.body && req.body.name)
Is `user` the one who made the request? The name is not clear enough.

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +    name: req.query.name || (req.body && req.body.name)
Also, I think that is a good way to send a `user` object. I think it should be sent inside a header instead.

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +    name: req.query.name || (req.body && req.body.name)
Do we want some kind of validation on this input? @yubbi99

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +    name: req.query.name || (req.body && req.body.name)
This should be discussed with a larder forum because that relates to all of the API endpoint, and not just to this function @yubbi99

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/index.ts
> +    };
What if the malshab was not found?
Shouldn't you return a 404 error?

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/utils.ts
> +export const gePermissions = (role :number): string[] => {
So does `getPermissions` returns an array of Malshab keys??
This is **very** confusing. 
Please change the names of the function and the `Permissionroles` object, and add documentation on this function.

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/utils.ts
> +export const malshabFilter = (malshab: (MalshabInterface & mongoose.Document<any>), allowedKeys: string[]): Partial<MalshabInterface> | undefined => {
Should give a better name for this function.
Maybe filterMalshab keys?

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/utils.ts
> +    return undefined;
why is that necessary?

2021-02-10 15:48 UTC, yonatandt commented on getMalshab/sample.dat
> +}
Either put a sample or remove it from git.

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/config.ts
> +const rolePermissions = {
This name is very misleading.

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/malshab.interface.ts
> +export default MalshabInterface;
I am not sure this is the correct Interface.
Anyway it should sit in a shared location to all of the function app @AdarPascal .

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/types.ts
> +    check = 2,
?

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/types.ts
> +export enum Permissionroles {
What does it mean?

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/types.ts
> +}
Oh wow.
I don't think we should care that much how is the malshab looks in this funciton app.

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/types.ts
> +}
Should sit in a shared location for the whole function app.

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/user.interface.ts
> +
Should sit in a shared location for the whole function app.

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/utils.ts
> +    // return Object.keys(filtered).length? filtered : null
remove comment

2021-02-10 15:48 UTC, yonatandt commented on getMalshabShared/utils.ts
> +    }
You better use a function that does it automatically instead of a switch-case.

2021-02-10 15:48 UTC, yonatandt commented on getMalshabs/index.ts
> +const httpTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
Give a better name.

2021-02-10 22:09 UTC, lustigy96 commented on getMalshab/index.ts
> +    name: req.query.name || (req.body && req.body.name)
Think that too.

2021-02-10 22:12 UTC, lustigy96 commented on getMalshabShared/types.ts
> +}
Yes of course, I thought that we will do it all together. We all use those types. I can put it in another folder for now (?)

2021-02-10 22:12 UTC, lustigy96 commented on getMalshabShared/user.interface.ts
> +
Yes of course, I thought that we will do it all together. We all use those types. I can put it in another folder for now (?)

2021-02-10 22:13 UTC, lustigy96 commented on getMalshabShared/utils.ts
> +    // return Object.keys(filtered).length? filtered : null
did that on the next commit :))

2021-02-10 22:20 UTC, lustigy96 commented on getMalshab/index.ts
> +    name: req.query.name || (req.body && req.body.name)
didn't get that

2021-02-11 11:53 UTC, lustigy96 commented on getMalshab/index.ts
> +  await mongoose.connect("mongodb://"+ process.env.COSMOSDB_HOST+":"+process.env.COSMOSDB_PORT+"/"+process.env.COSMOSDB_DBNAME+"?ssl=true&replicaSet=globaldb&retryWrites=false", {
done :)

2021-02-14 08:10 UTC, closed without merging