Units api
alphayesodot/itur-be-functionapp pull request #14
Opened 2021-02-11 13:44 UTC by carmeltsadok

2021-02-11 19:39 UTC, vitaly-furman commented on CreateUnit/index.ts
> +import { FunctionError, ValidationError, DuplicateUnitNameError, getResObject } from '../shared/services/error';
I think you can put getResObject function in a different file, it's not always an error.

2021-02-11 19:42 UTC, vitaly-furman commented on DeleteUnitById/index.ts
> +import * as mongoose from 'mongoose';
import not used.

2021-02-11 19:44 UTC, vitaly-furman commented on GetUnitById/index.ts
> +import * as mongoose from 'mongoose';
import not used.

2021-02-11 19:47 UTC, carmeltsadok commented on DeleteUnitById/index.ts
> +import * as mongoose from 'mongoose';
Used in unitId's type- mongoose.Types.ObjectId

2021-02-11 19:47 UTC, carmeltsadok commented on GetUnitById/index.ts
> +import * as mongoose from 'mongoose';
Used in unitId's type- mongoose.Types.ObjectId

2021-02-11 20:07 UTC, vitaly-furman commented on UpdateUnitById/index.ts
> +        const unit: IUnit = await UnitModel.findOneAndUpdate({ _id: unitId }, { $set: req.body })
$set is not really required here, it will only update the properties that are in req.body even without it.

2021-02-11 20:12 UTC, vitaly-furman commented on UpdateUnitById/index.ts
> +        const updatedUnit: IUnit = await UnitModel.findById(unitId).exec();
instead of doing another db request it can be replaced by adding findOneAndUpdate({ _id: unitId }, { $set: req.body}, {new: true}}, it will return you the new and updated document

2021-02-11 20:18 UTC, vitaly-furman commented on shared/services/error.ts
> +        super(parseInt(process.env.SERVER_ERROR_CODE, 10), 'Unit not found');
not found should be different error code than

2021-02-11 20:21 UTC, vitaly-furman commented on DeleteUnitById/index.ts
> +import * as mongoose from 'mongoose';
I think it's too much to import just to declare one type of a const but ok

2021-02-11 21:51 UTC, vitaly-furman submitted a review, later dismissed
Good overall, minor changes.

2021-03-07 16:28 UTC, lustigy96 requested changes

2021-03-07 16:28 UTC, lustigy96 commented on .eslintrc.js
> +};
don't know where to write it because i cant see the '.gitignoe' file here 
I think you should add the 'dist' dir to the gitignore file

2021-04-06 07:00 UTC, carmeltsadok commented on CreateUnit/joi.ts
> +export default createUnitSchema;
There is no requirement for that

2021-04-06 09:44 UTC, yonatandt commented on CreateUnit/index.ts
> +                status: 401,
```suggestion
                status: 403,
```

2021-04-06 11:25 UTC, yonatandt requested changes

2021-04-06 11:25 UTC, yonatandt commented on CreateUnit/index.ts
> +                status: 403,
Why 403?

2021-04-06 11:25 UTC, yonatandt commented on CreateUnit/index.ts
> +        const unit: Unit | void = await UnitModel.create(req.body).catch((e) => {
You should stay with `error`

2021-04-06 11:25 UTC, yonatandt commented on CreateUnit/index.ts
> +            status: 200,
```suggestion
            status: 201,
```

2021-04-06 11:25 UTC, yonatandt commented on CreateUnit/index.ts
> +            status: 200,
Better return status `Created`

2021-04-06 11:25 UTC, yonatandt commented on GetMyUnit/index.ts
> +                body: new FunctionError("The user doesn't has a unit", 'Get My Unit', "The user doesn't has a unit").message,
```suggestion
                body: new FunctionError("The user doesn't has a unit", 'Get My Unit', "The user doesn't have a unit").message,
```

2021-04-06 11:25 UTC, yonatandt commented on GetMyUnit/index.ts
> +                body: new FunctionError("The user doesn't has a unit", 'Get My Unit', "The user doesn't has a unit").message,
There are more users that may not have a unit. You should check that as well.

2021-04-06 11:25 UTC, yonatandt commented on GetMyUnit/index.ts
> +                body: new FunctionError('Unit Not Found', 'Get My Unit', 'Unit not found').message,
```suggestion
                body: new FunctionError('Unit Not Found', 'Get My Unit', `Unit: ${user.unitId} not found`).message,
```

2021-04-06 11:25 UTC, yonatandt commented on GetUnitById/index.ts
> +                body: new FunctionError('Unauthorized user', 'Get Unit By Id', 'The user is unauthorized').message,
Should be `Forbiden`

2021-04-06 11:25 UTC, yonatandt commented on GetUnitById/function.json
> +      "route": "units/{id}"
```suggestion
      "route": "unit/{id}"
```

2021-04-06 11:25 UTC, yonatandt commented on GetUnits/function.json
> +      "route": "units/"
```suggestion
      "route": "unit/"
```

2021-04-06 11:25 UTC, yonatandt commented on UpdateUnitById/function.json
> +      "route": "units/{id}"
```suggestion
      "route": "unit/{id}"
```

2021-04-06 11:25 UTC, yonatandt commented on UpdateUnitById/index.ts
> +                body: new FunctionError('Unit Not Found', 'Update Unit By Id', 'Unit not found').message,
```suggestion
                body: new FunctionError('Unit Not Found', 'Update Unit By Id', `Unit ${unitId} not found`).message,
```

2021-04-06 11:25 UTC, yonatandt commented on package.json
> +  "name": "units-api",
```suggestion
  "name": "itur-be-functionapp",
```

2021-04-06 11:25 UTC, yonatandt commented on UpdateUnitById/joi.ts
> +const objectIdType: Joi.StringSchema = Joi.string().regex(/^[a-f\d]{24}$/i);
Maybe you can put it in a shared location.

2021-04-12 14:17 UTC, lustigy96 approved these changes

2021-04-12 14:43 UTC, merged