Events api
alphayesodot/itur-be-functionapp pull request #15
Opened 2021-02-11 19:31 UTC by vitaly-furman

2021-02-18 08:37 UTC, carmeltsadok requested changes

2021-02-18 08:37 UTC, carmeltsadok commented on getEvents/index.ts
> +        await getConnection();
Move it after the validation so you won't connect to DB for no reason.

2021-02-18 08:37 UTC, carmeltsadok commented on getEvent/sample.dat
> +{
Remove this file if there is no sample

2021-02-18 08:37 UTC, carmeltsadok commented on getEvents/sample.dat
> +{
Remove this file if there is no sample

2021-02-18 08:37 UTC, carmeltsadok commented on updateEvent/sample.dat
> +{
Remove this file if there is no sample

2021-02-18 08:37 UTC, carmeltsadok commented on getEvent/index.ts
> +        await getConnection();
Move it after the validation so you won't connect to DB for no reason.

2021-02-18 08:37 UTC, carmeltsadok commented on updateEvent/index.ts
> +        await getConnection();
Move it after the validation so you won't connect to DB for no reason.

2021-02-18 08:37 UTC, carmeltsadok commented on getEvent/index.ts
> +    return { status: statusCode ?? process.env.SERVER_ERROR_CODE, body: responseMessage };
There is no reason to save status codes in the env file, it won't change. 
I write this here but you should change it in the other files as well.

```suggestion
    return { status: statusCode ?? 500, body: responseMessage };
``

2021-02-18 08:37 UTC, carmeltsadok commented on getEvent/index.ts
> +            throw new FunctionError(parseInt(process.env.VALIDATION_ERROR_CODE, 10), error.message);
```suggestion
           context.res = getResObject(400, error.message)
            context.done();
```

There is no need to throw an error in a try-catch section, you can send the res directly.
I write this here but you should change it in the other files as well.

2021-02-18 08:37 UTC, carmeltsadok commented on updateEvent/index.ts
> +        const updatedEvent = await EventModel.findOneAndUpdate({ _id: eventId }, event, { new: true, rawResult: true }).exec();
Why rawResult: true?

2021-05-04 11:48 UTC, carmeltsadok requested changes
Pull the dev and change directories names to PascalCase @vitaly-furman

2021-05-04 13:18 UTC, carmeltsadok requested changes

2021-05-04 13:18 UTC, carmeltsadok commented on addEventResult/index.ts
> +            throw new ObjectNotFoundFunctionError(functionName, 'Event', eventId);
It can also be a validation error in case the interviewer is not in event

2021-05-04 13:18 UTC, carmeltsadok commented on addEventResult/index.ts
> +        const { eventResult } = req.body;
```suggestion
        const { result } = req.body;
```
I think it's more clear

2021-05-04 13:18 UTC, carmeltsadok commented on addEventResult/joi.ts
> +const note = {
Isn't it need to be `Joi.object()`?

2021-05-04 13:18 UTC, carmeltsadok commented on getEvent/index.ts
> +            throw new FunctionError(functionName, 'Cannot get events for now');
Change to forbidden error

2021-05-04 13:18 UTC, carmeltsadok commented on addEventInterviewer/index.ts
> +            if (eventNode.unitId.toString() !== user.unitId?.toString()) {
```suggestion
            if (eventNode.unitId?.toString() !== user.unitId?.toString()) {
```

You did it on `getEvent`

2021-05-04 13:18 UTC, carmeltsadok commented on getEvent/index.ts
> +        }
Change to a switch case

2021-05-04 13:18 UTC, carmeltsadok commented on addEventInterviewer/index.ts
> +        }
Change to a switch case

2021-05-04 13:18 UTC, carmeltsadok commented on package.json
> +  "name": "events-api",
```suggestion
  "name": "itur-be-functionapp",
```

2021-05-04 13:18 UTC, carmeltsadok commented on removeEventInterviewer/index.ts
> +            throw new FunctionError(functionName, 'Cannot remove event Interviewers');
Change to forbidden error

2021-05-04 13:18 UTC, carmeltsadok commented on removeEventInterviewer/index.ts
> +const removeEventInterviewer: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
Add role validation:
RIU - validate that the requester is in the same unit as the event.
RIU-A - validate that the requester is in the same nodeGroup as the event.

2021-05-04 13:18 UTC, carmeltsadok commented on getEvents/index.ts
> +        }
Change to forbidden error.
Also, there is a change that more roles will be added in the future, so we need to check which roles are authorized and not which can't.

2021-05-04 13:18 UTC, carmeltsadok commented on getEvents/index.ts
> +        }
Move it to the top

2021-05-04 13:18 UTC, carmeltsadok commented on getEvents/index.ts
> +            // TODO: add populated docuemnt to mongoose schema for strong typing
```suggestion
```

2021-05-13 06:15 UTC, carmeltsadok requested changes

2021-05-13 06:15 UTC, carmeltsadok commented on removeEventInterviewer/index.ts
> +        const eventNode = await NodeModel.findById(event.node.id).exec();
Check if node exist

2021-05-13 06:15 UTC, carmeltsadok commented on getEvent/index.ts
> +        const eventNode = await nodeModel.findOne({ id: event.node.id }).exec();
Check if node exist

2021-05-13 06:15 UTC, carmeltsadok commented on shared/event/event.model.ts
>                  ref: collectionNames.node,
The ref doesn't get the object id?

2021-05-20 13:50 UTC, carmeltsadok approved these changes

2021-05-20 15:30 UTC, lustigy96 requested changes

2021-05-20 15:30 UTC, lustigy96 commented on shared/event/event.model.ts
>                  ref: collectionNames.node,
There is no point of using refs. since we use id and not _id... 
The ref is to _id and not to the other fields...

2021-05-20 15:30 UTC, lustigy96 commented on shared/event/event.model.ts
>                  ref: collectionNames.malshab,
There is no point of using refs. since we use id and not _id...
The ref is to _id and not to the other fields...

2021-05-22 16:04 UTC, vitaly-furman commented on shared/event/event.model.ts
>                  ref: collectionNames.node,
It's required here because the field needs to be populated and for that it needs the ref.

2021-05-22 16:05 UTC, vitaly-furman commented on shared/event/event.model.ts
>                  ref: collectionNames.malshab,
Same as above, if someone ever needs to execute a query and populate that field the ref is needed.

2021-05-23 11:53 UTC, yonatandt requested changes

2021-05-23 11:53 UTC, yonatandt commented on GetEvent/index.ts
> +                throw new FunctionError(functionName, 'User is not in the unit of event');
```suggestion
                throw new ForbiddenFunctionError(functionName, 'User is not in the unit of event');
```

2021-05-23 11:53 UTC, yonatandt commented on GetEvent/index.ts
> +                throw new FunctionError(functionName, 'User is not in the nodeGroup of the event');
```suggestion
                throw new ForbiddenFunctionError(functionName, 'User is not in the nodeGroup of the event');
```

2021-05-23 11:53 UTC, yonatandt commented on GetEvent/index.ts
> +        return { body: event };
Remember to filter out the `results` from the event object when the requesting user is not `Technical`

2021-05-23 11:53 UTC, yonatandt commented on GetEvents/index.ts
> +        }
It is not just `Mada` & `Itur` who can't get events. The intent was it is not decided if and how they will get the events yet.

2021-05-23 11:53 UTC, yonatandt commented on GetEvents/index.ts
> +        }
You should do it in a switch-case (by role) instead.

2021-05-23 11:53 UTC, yonatandt commented on GetEvents/joi.ts
> +}).unknown();
The validation needs to be more complicated than that. There must be a `date` field if there is no `malshabId`.

2021-05-23 11:53 UTC, yonatandt commented on GetEvents/index.ts
> +    }
What if no date is given?

2021-05-23 11:53 UTC, yonatandt commented on RemoveEventInterviewer/index.ts
> +                throw new FunctionError(functionName, `User is not in the unit of event`);
```suggestion
                throw new ForbiddenFunctionError(functionName, `User is not in the unit of event`);
```

2021-05-23 11:53 UTC, yonatandt commented on RemoveEventInterviewer/index.ts
> +                throw new FunctionError(functionName, `User is not in the nodeGroup of event`);
```suggestion
                throw new ForbiddenFunctionError(functionName, `User is not in the nodeGroup of event`);
```

2021-05-23 11:53 UTC, yonatandt commented on shared/services/db.ts
> +export default getConnection;
This function already exists in `/shared/mongoose.ts`

2021-05-23 13:37 UTC, carmeltsadok requested changes

2021-05-23 13:37 UTC, carmeltsadok commented on AddEventResult/joi.ts
> +            questionnaire: Joi.array().items(objectId).optional(),
Remove `questionnaire` as an option

2021-05-30 14:39 UTC, vitaly-furman commented on GetEvents/index.ts
> +    }
If no date is provided it will not add time to the query.

2021-05-30 14:48 UTC, vitaly-furman commented on AddEventResult/joi.ts
> +            questionnaire: Joi.array().items(objectId).optional(),
why?

2021-05-30 14:48 UTC, vitaly-furman commented on AddEventResult/joi.ts
> +            questionnaire: Joi.array().items(objectId).optional(),
אל תבלבלי במוח

2021-05-30 15:54 UTC, carmeltsadok commented on AddEventResult/joi.ts
> +            questionnaire: Joi.array().items(objectId).optional(),
We talked about it. When someone is creating a questionnaire, a message sends to a queue and than it automatically updates the event’s result. So, there is no option to add it as a result by a request.

2021-05-30 18:13 UTC, vitaly-furman commented on AddEventResult/joi.ts
> +            questionnaire: Joi.array().items(objectId).optional(),
ok

2021-05-30 19:59 UTC, carmeltsadok requested changes

2021-05-30 19:59 UTC, carmeltsadok commented on shared/services/db.ts
> +export default getConnection;
@vitaly-furman

2021-05-31 09:15 UTC, vitaly-furman commented on GetEvents/index.ts
> +        }
For now it will remain the same and when we decide I'll change based on the requirements.

2021-05-31 11:13 UTC, vitaly-furman commented on GetEvent/index.ts
> +        return { body: event };
Ok, opened an issue about that, will filter out when it will be decided.

2021-05-31 11:36 UTC, carmeltsadok approved these changes

2021-05-31 11:36 UTC, carmeltsadok commented on GetEvent/index.ts
> +                const eventNodeGroup = NodegroupModel.find({ _id: eventNode.nodeGroupId, usersIds: user.id }).exec();
```suggestion
                const eventNodeGroup = NodegroupModel.find({ id: eventNode.nodeGroupId, usersIds: user.id }).exec();
```

2021-05-31 13:54 UTC, lustigy96 approved these changes

2021-06-07 10:05 UTC, carmeltsadok approved these changes

2021-06-09 12:55 UTC, merged