Feat/question table
alphayesodot/itur-be-functionapp pull request #157
Opened 2021-08-31 14:55 UTC by lustigy96

2021-08-31 15:17 UTC, carmeltsadok requested changes

2021-08-31 15:17 UTC, carmeltsadok commented on shared/question/question.ts
> +    multipleChoiseTable = 'MULTIPLE_CHOISE_TABLE',
Change to multiple **choice** table

2021-09-05 08:34 UTC, PCOffline requested changes

2021-09-05 08:34 UTC, PCOffline commented on shared/question/question.ts
> +    }
Use `Array.prototype.every` instead. It's a significantly faster method.

```suggestion
        return this.rows.every((row, idx) => this.answer[idx] > 0 && this.answer[idx] < this.columns.length  && (!row.required || this.answer[idx])) && super.isAnswerValid();
    }
```

2021-09-05 08:34 UTC, PCOffline commented on shared/question/question.ts
> +     * answer is a 2-dimetions array, size: (rows x ?), each sub array includes the indexes of the picked column, for each row accordingly     *
2-dimensional array*

2021-09-05 08:34 UTC, PCOffline commented on shared/question/question.ts
> +        const answerValidation = this.rows.map((row, idx) => {
Again, use `Array.prototype.every` instead.

2021-09-05 08:34 UTC, PCOffline commented on shared/question/question.ts
> +        const answerValidation = this.rows.map((row, idx) => {
Use `Array.prototype.every` instead.

2021-09-05 13:10 UTC, PCOffline commented on shared/question/question.ts
> +                (!this.required || !(this.answer[idx].includes('') || !this.answer[idx].includes(undefined))), // if answer is required, validate no undefineds ot empty strings
`!(this.answer[idx].includes('') || !this.answer[idx].includes(undefined))` will be true if the answer includes undefined.
Also, `String.includes(undefined)` will be true only if it includes the string `'undefined'`, is this the behaviour you expect?

2021-09-14 13:45 UTC, carmeltsadok approved these changes

2021-09-19 10:30 UTC, PCOffline commented on shared/question/question.ts
> +                (!this.required || !(this.answer[idx].includes('') || !this.answer[idx].includes(undefined))), // if answer is required, validate no undefineds ot empty strings
This is still unfixed

2021-09-19 13:58 UTC, carmeltsadok commented on shared/question/question.ts
> +                (!this.required || !(this.answer[idx].includes('') || !this.answer[idx].includes(undefined))), // if answer is required, validate no undefineds ot empty strings
@lustigy96

2021-09-29 08:09 UTC, lustigy96 commented on shared/question/question.ts
> +                (!this.required || !(this.answer[idx].includes('') || !this.answer[idx].includes(undefined))), // if answer is required, validate no undefineds ot empty strings
this.answer[idx] is an array of strings and not a string.

2021-09-29 08:14 UTC, PCOffline commented on shared/question/question.ts
> +                (!this.required || !(this.answer[idx].includes('') || !this.answer[idx].includes(undefined))), // if answer is required, validate no undefineds ot empty strings
Okay

2021-09-29 08:15 UTC, PCOffline approved these changes

2021-09-29 14:42 UTC, merged