Nodes groups api
alphayesodot/itur-be-functionapp pull request #16
Opened 2021-02-11 20:41 UTC by maykremer

2021-02-11 22:00 UTC, vitaly-furman commented on UpdateNodesGroup/index.ts
> +                throw new FunctionError(404, err.message);
You already have catch at the end of the function so it will catch the error if findById fails

2021-02-11 22:01 UTC, vitaly-furman commented on UpdateNodesGroup/index.ts
> +                throw new FunctionError(404, err.message);
if findById doesn't find anything it will not throw an error, so you just need to check, if(existNodesGroup) to see if the query was successful.

2021-02-11 22:01 UTC, vitaly-furman commented on UpdateNodesGroup/index.ts
> +            throw new FunctionError(404, err.message);
same here

2021-02-11 22:02 UTC, vitaly-furman commented on UpdateNodesGroup/index.ts
> +            throw new FunctionError(404, err.message);
and here

2021-02-11 22:05 UTC, vitaly-furman commented on GetUserNodesGroups/index.ts
> +            });
check if(userNodesGroup) instead

2021-02-11 22:14 UTC, vitaly-furman commented on UpdateNodesGroup/index.ts
> +        context.res = { status: error.code, body: error.message };
by default Error object has no 'code' property, that's why we created a FunctionError function that inherits from error and adds 'code' property to it. 
If an error occurs in the function and it's not something that we threw it will not have 'code' and error.code = undefined. In that case we will get the response with the message but the status code that the client sees will be 200 which means that everything is ok.
Just check that it has a code if not add some default value, like 500. you can see in my branch I did something similar.

2021-02-11 22:16 UTC, vitaly-furman commented on GetUserNodesGroups/index.ts
> +            throw new FunctionError(400, error.message);
better to get the code from environment variable

2021-02-11 22:17 UTC, vitaly-furman commented on GetNodesGroups/index.ts
> +        .then(async () => {
don't need .then if you have await

2021-02-11 22:17 UTC, vitaly-furman commented on GetNodesGroups/index.ts
> +                    throw new FunctionError(404, err.message);
replace catch with if

2021-03-07 17:31 UTC, lustigy96 requested changes

2021-03-07 17:31 UTC, lustigy96 commented on AddNodeToNodesGroup/index.ts
> +            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group unit not include this node id' };
```suggestion
            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group unit does not include this node id' };

```

2021-03-07 17:31 UTC, lustigy96 commented on AddNodeToNodesGroup/index.ts
> +            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Node already exist in nodes group' };
```suggestion
            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Node already exists in nodes group' };

```

2021-03-07 17:31 UTC, lustigy96 commented on AddNodeToNodesGroup/index.ts
> +            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group not update' };
```suggestion
            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group did not update' };

```

2021-03-07 17:31 UTC, lustigy96 commented on AddOwnerToNodesGroup/index.ts
> +            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Unit not include this owner id' };
```suggestion
            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Unit does not include this owner id' };

```

2021-03-07 17:31 UTC, lustigy96 commented on AddOwnerToNodesGroup/index.ts
> +            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Owner already exist in nodes group' };
```suggestion
            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Owner already exists in nodes group' };

```

2021-03-07 17:31 UTC, lustigy96 commented on AddOwnerToNodesGroup/index.ts
> +            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group not update' };
```suggestion
            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group did not update' };

```

2021-03-07 17:31 UTC, lustigy96 commented on CreateNodesGroup/utils/req.validation.ts
> +export default nodesGroupValidation;
I think you can put this file out of the utils directory (like you did in the AddNodeToNodesGroup function)

2021-03-07 17:31 UTC, lustigy96 commented on CreateNodesGroup/index.ts
> +            const createdNodesGropp: INodesGroup = await NodesGroupModel.create(nodesGroup);
```suggestion
            const createdNodesGroup: INodesGroup = await NodesGroupModel.create(nodesGroup);

```

2021-03-07 17:31 UTC, lustigy96 commented on CreateNodesGroup/index.ts
> +            if (!createdNodesGropp) {
```suggestion
            if (!createdNodesGroup) {

```

2021-03-07 17:31 UTC, lustigy96 commented on CreateNodesGroup/index.ts
> +            context.res = { status: process.env.SUCCESS_CODE, body: createdNodesGropp };
```suggestion
            context.res = { status: process.env.SUCCESS_CODE, body: createdNodesGroup };

```

2021-03-07 17:31 UTC, lustigy96 commented on CreateNodesGroup/index.ts
> +                context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group not create' };
```suggestion
                context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group didn't created' };

```

2021-03-07 17:31 UTC, lustigy96 commented on DeleteInterviewerFromNodesGroup/index.ts
> +            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Interviewer not deleted' };
```suggestion
            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Interviewer wasn't deleted' };

```

2021-03-07 17:31 UTC, lustigy96 commented on DeleteInterviewerFromNodesGroup/index.ts
> +            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group not update' };
```suggestion
            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group did not update' };

```

2021-03-07 17:31 UTC, lustigy96 commented on DeleteNodeFromNodesGroup/index.ts
> +            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group not update' };
```suggestion
            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group did not update' };

```

2021-03-07 17:31 UTC, lustigy96 commented on DeleteNodeFromNodesGroup/index.ts
> +            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Node not deleted' };
```suggestion
            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Node wasn't deleted' };

```

2021-03-07 17:31 UTC, lustigy96 commented on DeleteOwnerFromNodesGroup/index.ts
> +            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Owner not exist in nodes group' };
```suggestion
            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Owner does not exist in nodes group' };

```

2021-03-07 17:31 UTC, lustigy96 commented on DeleteOwnerFromNodesGroup/index.ts
> +            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Owner not deleted' };
```suggestion
            context.res = { status: process.env.SERVER_ERROR_CODE, body: 'Owner was not deleted' };

```

2021-03-07 17:31 UTC, lustigy96 commented on DeleteOwnerFromNodesGroup/index.ts
> +            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group not update' };
```suggestion
            context.res = { status: process.env.NOT_FOUND_CODE, body: 'Nodes group didn't updated' };

```

2021-04-19 07:55 UTC, carmeltsadok requested changes

2021-04-19 07:55 UTC, carmeltsadok commented on AddNodeToNodeGroup/function.json
> +      "name": "req",
```suggestion
      "name": "addNodeToNodeGroup",
```

2021-04-19 07:55 UTC, carmeltsadok commented on AddNodeToNodeGroup/index.ts
> +            throw new ObjectNotFoundFunctionError(functionName, 'node group', nodeGroupId);
```suggestion
            throw new ObjectNotFoundFunctionError(functionName, 'nodeGroup', nodeGroupId);

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddNodeToNodeGroup/index.ts
> +            throw new ObjectAlreadyExistInArrayFunctionError(functionName, nodeId, ' nodeGroup nodesIds');
```suggestion
            throw new ObjectAlreadyExistInArrayFunctionError(functionName, nodeId, 'nodeGroup's nodesIds');

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddNodeToNodeGroup/index.ts
> +            throw new ObjectNotFoundFunctionError(functionName, 'node group ', nodeGroupId);
```suggestion
            throw new ObjectNotFoundFunctionError(functionName, 'nodeGroup ', nodeGroupId);

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddNodeToNodeGroup/req.validation.ts
> +const reqValidation = Joi.object({
```suggestion
const addNodeToNodeGroupSchema= Joi.object({
```
Change file name to `joi.ts`

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/function.json
> +      "name": "req",
```suggestion
      "name": "addUserToNodeGroup",
```

2021-04-19 07:55 UTC, carmeltsadok commented on AddNodeToNodeGroup/index.ts
> +        const validationError: ValidationError = reqValidation.validate(req).error;
```suggestion
        const validationError: ValidationError = addNodeToNodeGroupSchema.validate(req).error;

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +        const validationError: ValidationError = reqValidation.validate(req).error;
```suggestion
        const validationError: ValidationError = addUserToNodeGroupSchema.validate(req).error;

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +        const nodeGroup: NodeGroup | void = await NodeGroupModel.findOne({ id: nodeGroupId }).exec();
Change to find by id

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +            throw new ObjectNotFoundFunctionError(functionName, 'node group', nodeGroupId);
```suggestion
            throw new ObjectNotFoundFunctionError(functionName, 'nodeGroup', nodeGroupId);

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +            throw new ObjectAlreadyExistInArrayFunctionError(functionName, userId, ' nodeGroup usersIds');
```suggestion
            throw new ObjectAlreadyExistInArrayFunctionError(functionName, userId, 'nodeGroup's usersIds');

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +            throw new ObjectNotFoundFunctionError(functionName, 'node group', nodeGroupId);
```suggestion
            throw new ObjectNotFoundFunctionError(functionName, 'nodeGroup', nodeGroupId);

```

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/req.validation.ts
> +const reqValidation = Joi.object({
```suggestion
const addUserToNodeGroupSchema= Joi.object({
```
Change file name to `joi.ts`

2021-04-19 07:55 UTC, carmeltsadok commented on AddUserToNodeGroup/req.validation.ts
> +        userId: Joi.string().regex(/^[a-f\d]{24}$/i),
Add `objectIdType` const

2021-04-19 07:55 UTC, carmeltsadok commented on CreateNodeGroup/function.json
> +      "name": "req",
```suggestion
      "name": "createNodeGroup",
```

2021-04-19 07:55 UTC, carmeltsadok commented on CreateNodeGroup/index.ts
> +const createNodeGroup: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const createNodeGroup: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {

```

2021-04-19 07:55 UTC, carmeltsadok commented on CreateNodeGroup/index.ts
> +        const recievedNodeGroup: NodeGroup = req.body;
```suggestion
        const receivedNodeGroup: NodeGroup = req.body;

```

2021-04-19 07:55 UTC, carmeltsadok commented on CreateNodeGroup/index.ts
> +        const unit: Unit | void = await UnitModel.findOne({ id: recievedNodeGroup.unitId });
Change to find by id

2021-04-19 11:13 UTC, yonatandt commented on AddNodeToNodeGroup/function.json
> +      "name": "req",
@carmeltsadok  why?

2021-04-19 11:41 UTC, yonatandt requested changes

2021-04-19 11:41 UTC, yonatandt commented on AddNodeToNodeGroup/index.ts
> +const addNodeToNodeGroup: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
We decided to add a node to a nodeGroup by updating the node object: `/node/:id` with an optional `nodeGroup` body param. Therefore this function is not needed.

2021-04-19 11:41 UTC, yonatandt commented on AddUserToNodeGroup/index.ts
> +        const validationError: ValidationError = reqValidation.validate(req).error;
In my opinion, it is really not neccesarry to validate the request params here...
It is just an opportunity for future bugs.

2021-04-20 07:40 UTC, carmeltsadok requested changes

2021-04-20 07:40 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +        const { userId } = context.bindingData;
```suggestion
        const { nodeGroupId, userId } = context.bindingData;

```

2021-04-20 07:40 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +        const userToAdd: User | void = await UserModel.findById(userId).exec();
Change to identity number
```suggestion
        const userToAdd: User = await UserModel.findById(userId).exec();

```
Remove every `| void`

2021-04-20 08:52 UTC, carmeltsadok requested changes

2021-04-20 08:52 UTC, carmeltsadok commented on CreateNodeGroup/index.ts
> +        }
When creating a nodeGroup, we won't send users. We have add and remove user functions.

2021-04-20 08:52 UTC, carmeltsadok commented on CreateNodeGroup/index.ts
> +        }
The unit is deferred from the user unit, so you need to add the `unitId` by yourself to the object, and there is no need for validation.

2021-04-20 08:52 UTC, carmeltsadok commented on CreateNodeGroup/req.validation.ts
> +    usersIds: Joi.array().items(objectIdType).required(),
```suggestion
    name: Joi.string().required(),
```

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteNodeGroup/index.ts
> +
You need to verify that there are no nodes in the nodeGroup

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteUserFromNodeGroup/function.json
> +  "scriptFile": "../dist/DeleteUserFromNodeGroup/index.js"
```suggestion
  "scriptFile": "../dist/RemoveUserFromNodeGroup/index.js"
```

Change in all files and directories

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteUserFromNodeGroup/index.ts
> +        const { userId } = context.bindingData;
```suggestion
        const { nodeGroupId, userId  } = context.bindingData;

```

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteUserFromNodeGroup/index.ts
> +        const nodeGroup: NodeGroup | void = await NodeGroupModel.findOne({ id: nodeGroupId }).exec();
Change to findById

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteUserFromNodeGroup/index.ts
> +        const userToDelete: User | void = await UserModel.findById(userId).exec();
Change to findOne, by identity number

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteUserFromNodeGroup/index.ts
> +        }
Unnecessary

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteUserFromNodeGroup/index.ts
> +        }
Unnecessary

2021-04-20 08:52 UTC, carmeltsadok commented on DeleteUserFromNodeGroup/req.validation.ts
> +        userId: objectIdType.required(),
```suggestion
        nodeGroupId: objectIdType.required(),
        userId: Joi.string().required(),
```

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupById/index.ts
> +        const nodeGroup: NodeGroup | void = await nodeGroupModel.findOne({ id }).exec();
Change to findById

2021-04-20 08:52 UTC, carmeltsadok commented on shared/error/error.ts
> +
Unnecessary

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupUsers/index.ts
> +        }
`userIds` array can be empty

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupUsers/index.ts
> +
Check by role: 
RIU: Validate the the nodeGroup is in the requesting user's unit
RIU-A / PR: Validate that the requesting users is in the nodeGroup

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupsByUnit/index.ts
> +        const { unitId } = req.body;
The `unitId` comes from the requesting user

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupsByUnit/index.ts
> +        const unit: Unit | void = await unitModel.findOne({ id: unitId }).exec();
Change to `findById`

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupsByUnit/index.ts
> +
If the user is an interviewer you need to return a single nodesGroup that he is in.

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupsByUnit/index.ts
> +        }
The array can be empty

2021-04-20 08:52 UTC, carmeltsadok commented on GetNodeGroupsByUnit/req.validation.ts
> +export default getNodeGroupsByUnitSchema;
No need for joi validation here. There is no params or body

2021-04-21 14:50 UTC, carmeltsadok requested changes

2021-04-21 14:50 UTC, carmeltsadok commented on GetNodeGroupsByUnit/index.ts
> +        const unit: Unit = await unitModel.findOne({ id: unitId }).exec();
Change to `findById`

2021-04-22 05:31 UTC, yonatandt commented on AddUserToNodeGroup/function.json
> +      "name": "req",
Nope @carmeltsadok

2021-04-22 07:39 UTC, yonatandt requested changes

2021-04-22 07:39 UTC, yonatandt commented on GetNodeGroupUsers/index.ts
> +        }
No need.

2021-04-22 07:39 UTC, yonatandt commented on GetNodeGroupUsers/index.ts
> +                if (nodeGroup.unitId !== user.unitId) throw new Error(`nodeGroup ${id} and user ${user.id} not in the same unit`);
ValidationFunctionError

2021-04-22 07:39 UTC, yonatandt commented on GetNodeGroupUsers/index.ts
> +                if (nodeGroup.unitId !== user.unitId) throw new Error(`nodeGroup ${id} and user ${user.id} not in the same unit`);
```suggestion
                if (nodeGroup.unitId !== user.unitId) throw new Error(`The user ${user.id} is not in the unit of nodeGroup ${id}.`);

```

2021-04-22 07:39 UTC, yonatandt commented on GetNodeGroupUsers/index.ts
> +                if (!nodeGroup.usersIds.includes(user.id)) throw new Error(`user ${user.id} not in nodeGroup ${id}`);
ValidationFunctionError

2021-04-22 07:39 UTC, yonatandt commented on GetNodeGroupUsers/index.ts
> +                if (!nodeGroup.usersIds.includes(user.id)) throw new Error(`user ${user.id} not in nodeGroup ${id}`);
```suggestion
                if (!nodeGroup.usersIds.includes(user.id)) throw new Error(`The user ${user.id} must be in nodeGroup ${id}`);

```

2021-04-22 07:39 UTC, yonatandt commented on GetNodeGroupsByUnit/index.ts
> +        }
Not needed

2021-04-22 07:39 UTC, yonatandt commented on RemoveUserFromNodeGroup/index.ts
> +        }
No need

2021-04-22 07:39 UTC, yonatandt commented on RemoveUserFromNodeGroup/index.ts
> +        }
No need for this validation

2021-04-22 07:39 UTC, yonatandt commented on RemoveUserFromNodeGroup/index.ts
> +        }
No need for this validation

2021-04-22 07:39 UTC, yonatandt commented on RemoveUserFromNodeGroup/index.ts
> +            throw new Error(`user ${userId} have future interviews`);
ValidationFunctionError

2021-04-22 07:39 UTC, yonatandt commented on RemoveUserFromNodeGroup/index.ts
> +            throw new Error(`user ${userId} have future interviews`);
```suggestion
            throw new Error(`User ${userId} have future interviews. Please remove the user from those events before removing him from the nodeGroup`);

```

2021-04-22 07:39 UTC, yonatandt commented on RemoveUserFromNodeGroup/req.validation.ts
> +export default removeUserFromNodeGroupSchema;
As I said in the function file, there is no need for this validation

2021-04-22 07:39 UTC, yonatandt commented on RemoveUserFromNodeGroup/index.ts
> +
Verify that the requester is in the same unit as the nodeGroup.

2021-04-22 07:39 UTC, yonatandt commented on UpdateNodeGroup/req.validation.ts
> +        name: Joi.string().required(),
Same as the creation of a nodeGroup (minimum length for a name?)

2021-04-22 07:39 UTC, yonatandt commented on CreateNodeGroup/req.validation.ts
> +    name: Joi.string().required(),
Don't you want to give a minimum length to the name? @carmeltsadok @lustigy96

2021-04-22 07:39 UTC, yonatandt commented on shared/utils/req.id.validation.ts
> +export default reqIdValidation;
I believe there is no need for this function.

2021-04-22 07:41 UTC, yonatandt commented
@maykremer Your commits are not signed.
The PR won't be approved until you start singing them.

2021-04-25 10:02 UTC, yonatandt commented on AddUserToNodeGroup/index.ts
> +        const updatedNodeGroup: NodeGroup = await NodeGroupModel.findByIdAndUpdate(nodeGroupId, { usersIds: newUsersIdsList }, { new: true });
This is a bad practice. You should use `$push` instead.
Make sure you understand why it could cause a problem.

2021-04-27 07:45 UTC, carmeltsadok requested changes

2021-04-27 07:45 UTC, carmeltsadok commented on GetNodeGroupsByUnit/index.ts
> +const getNodeGroupByUnit: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const getNodeGroupByUnit: AzureFunction = async (_context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {

```

2021-04-27 07:45 UTC, carmeltsadok commented on GetNodeGroupById/index.ts
> +const getNodeGroupById: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const getNodeGroupById: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {

```

2021-04-27 07:45 UTC, carmeltsadok commented on DeleteNodeGroup/index.ts
> +const deleteNodeGroup: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const deleteNodeGroup: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {

```

2021-04-27 07:45 UTC, carmeltsadok commented on GetNodeGroupUsers/index.ts
> +const getNodeGroupUsers: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const getNodeGroupUsers: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {

```

2021-05-02 12:15 UTC, carmeltsadok requested changes

2021-05-02 12:15 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +        if (userToAdd.unitId !== nodeGroup.unitId) {
There is a need to check if the requester is in the same unit as the nodeGroup and as the user he wants to add.

2021-05-02 12:15 UTC, carmeltsadok commented on AddUserToNodeGroup/index.ts
> +        const userNodeGroup: NodeGroup = await NodeGroupModel.findOne({ usersIds: userId });
Do this request only if the `userToAdd` is an interviewer. And then verify if it exist in case he is an interviewer.

2021-05-02 12:15 UTC, carmeltsadok commented on GetNodeGroupsByUnit/index.ts
> +const getNodeGroupByUnit: AzureFunction = async (_context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const getNodeGroupsByUnit: AzureFunction = async (_context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {

```

2021-05-11 13:23 UTC, yonatandt submitted a review, later dismissed

2021-05-13 07:23 UTC, carmeltsadok approved these changes

2021-05-13 11:19 UTC, lustigy96 approved these changes

2021-05-13 11:23 UTC, carmeltsadok approved these changes

2021-05-13 11:23 UTC, lustigy96 approved these changes

2021-05-13 11:23 UTC, merged