added filtering to malshab attachments based on user role classification
alphayesodot/itur-be-functionapp pull request #161
Opened 2021-09-02 19:49 UTC by vitaly-furman

2021-09-14 13:45 UTC, carmeltsadok approved these changes

2021-09-19 10:35 UTC, PCOffline requested changes

2021-09-19 10:35 UTC, PCOffline commented on shared/classification/classification.ts
> +    return fileClassification === Classification.PRIVATE ? getDownloadClassification(user.role) === Classification.PRIVATE : true;
Simplify to
```suggestion
    return fileClassification === Classification.PUBLIC || getDownloadClassification(user.role) === Classification.PRIVATE;
```

2021-09-19 10:35 UTC, PCOffline commented on GetMalshab/index.ts
> +};
Convert to inline arrow function:

```suggestion
const filterMalshabAttachments = (user: User, malshab: Malshab) => malshab.attachments?.filter((attachmentKey) => isAttachmentKeyMatchingUserClassification(attachmentKey, user));
```

2021-09-19 15:40 UTC, vitaly-furman commented on GetMalshab/index.ts
> +};
no need, doesn't add any readability or performance

2021-09-20 11:28 UTC, PCOffline approved these changes

2021-09-29 07:49 UTC, merged