Function/get malshab
alphayesodot/itur-be-functionapp pull request #18
Opened 2021-02-14 09:44 UTC by lustigy96

I deleted the other branch and created a new one (with the fixes you suggested before - most of them). Tell you later the reason

2021-02-18 08:19 UTC, carmeltsadok requested changes

2021-02-18 08:19 UTC, carmeltsadok commented on getMalshabShared/utils.ts
> +export const getPermissions = (role: number): string[] => {
I would call this getAllowedKeysByRole

2021-02-18 08:41 UTC, carmeltsadok requested changes

2021-02-18 08:41 UTC, carmeltsadok commented on GetMalshab/index.ts
> +        const malshab = await MalshabModel.find({ taz });
You should throw an error if there is no malshab with that taz

2021-02-18 08:41 UTC, carmeltsadok commented on GetMalshab/index.ts
> +        const filtered = malshabFilter(malshab[0], getPermissions(user.role));
You should throw an error if the filter is undefined (which is possible according to malshabFilter function.

2021-02-18 08:41 UTC, carmeltsadok commented on GetMalshab/index.ts
> +const getMalshab: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
Wrap this function in try catch

2021-02-18 08:41 UTC, carmeltsadok commented on GetMalshabs/index.ts
> +const getMalshabs: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
Wrap this function in try catch

2021-03-08 09:36 UTC, lustigy96 commented on GetMalshab/index.ts
> +        };
here we dont need any validation - talking to Yuval..

2021-03-08 09:45 UTC, lustigy96 commented on GetMalshabs/index.ts
> +    const user: UserInterface = req.body && req.body.user;
We dont neet any validation here (talking to Yuval)

2021-03-08 09:46 UTC, lustigy96 commented on GetMalshabs/index.ts
> +    await getConnection();
Here there is no validation

2021-03-08 09:50 UTC, lustigy96 commented on shared/config.ts
> +const rolePermissions = {
This is a temporarily solution. The permissions rules are still ambivalent, so for now I won't change it. I think it wont be here anyway, it will be different.

2021-03-08 09:52 UTC, lustigy96 commented on GetMalshab/index.ts
> +        const malshab = await MalshabModel.find({ taz });
Not for now, talking to Yuval. Just reply and notify as I did here

2021-03-08 13:37 UTC, lustigy96 commented on getMalshabShared/utils.ts
> +export const getPermissions = (role: number): string[] => {
This is a temporarily solution. The permissions rules are still ambivalent, so for now I won't change it. I think it wont be here anyway, it will be different.

2021-03-30 21:43 UTC, closed without merging

2021-04-04 06:10 UTC, yonatandt commented
@lustigy96 why did you close this pr and open [another](#25)?