shared files for the whole function-app
alphayesodot/itur-be-functionapp pull request #19
Opened 2021-02-15 12:35 UTC by yonatandt

Signed-off-by: YonatanTal <yonatald@gmail.com>

2021-02-16 15:22 UTC, ShragaUser requested changes

2021-02-16 15:22 UTC, ShragaUser commented on shared/event/event.model.ts
> +import { IEvent, Status } from './event.interface';
Am I missing something? Is Status even defined in event.interface?

2021-02-16 15:22 UTC, ShragaUser commented on shared/event/event.model.ts
> +const EventSchema = new mongoose.Schema({
Also - why even use mongoose at all? Why not the actual mongodb driver? Using interfaces for validation in application level?

2021-02-16 15:22 UTC, ShragaUser commented on shared/malshab/malshab.interface.ts
> +    aptitudeTest?: AptitudeTest;
What is this? If it's a number shouldn't it have a "translated" property or be an enum?

2021-02-16 15:22 UTC, ShragaUser commented on shared/malshab/malshab.interface.ts
> +    pdfQuestionnaire?: string;
This is a url? If so - better to explicitly say so in property name

2021-02-16 15:22 UTC, ShragaUser commented on shared/mongoose.ts
> +import * as mongoose from 'mongoose';
Disconnection handling?
Error handling? 
Logs?

2021-02-16 15:22 UTC, ShragaUser commented on shared/event/event.model.ts
> +const EventModel = mongoose.model<IEvent & mongoose.Document>(process.env.EVENT_COLLECTION_NAME, EventSchema);
Shouldn't there be a default value for configurable elements? Maybe you should use a config file that holds all global configurations and handles them correctly?

2021-02-16 16:31 UTC, carmeltsadok requested changes

2021-02-16 16:31 UTC, carmeltsadok commented on shared/event/event.interface.ts
> +export interface Event {
```suggestion
export interface IEvent {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/error/error.ts
> +    constructor(message: string) {
What about error code?

2021-02-16 16:31 UTC, carmeltsadok commented on shared/malshab/malshab.interface.ts
> +interface AptitudeTest {
```suggestion
interface IAptitudeTest {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/malshab/malshab.interface.ts
> +export interface Address {
```suggestion
export interface IAddress {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/malshab/malshab.interface.ts
> +interface Language {
```suggestion
interface ILanguage {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/malshab/malshab.interface.ts
> +interface Grade {
```suggestion
interface IGrade {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/malshab/malshab.interface.ts
> +export default interface Malshab {
```suggestion
export default interface IMalshab {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/unit/unit.interface.ts
> +export default interface Unit {
```suggestion
export default interface IUnit {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/unit/unit.interface.ts
> +export default interface Unit {
Unit model is missing

2021-02-16 16:31 UTC, carmeltsadok commented on shared/nodesGroup/nodeGroups.interface.ts
> +export default interface NodesGroup {
```suggestion
export default interface INodesGroup {
```

2021-02-16 16:31 UTC, carmeltsadok commented on shared/nodesGroup/nodeGroups.interface.ts
> +export default interface NodesGroup {
Change file name to nodesGroup.interface.ts.
NodesGroup model is missing.

2021-02-21 07:59 UTC, yonatandt commented on shared/error/error.ts
> +    constructor(message: string) {
I think it is not mandatory and is not really needed.

2021-02-21 08:33 UTC, ShragaUser commented on shared/error/error.ts
> +    constructor(message: string) {
I think supporting added error code is a good idea. Might not be mandatory, but it is relevant...

2021-02-23 08:32 UTC, yubbi99 commented on shared/malshab/malshab.interface.ts
> +export type Gender = 1 | 2;
dont limit the malshab gender

2021-03-22 14:33 UTC, lustigy96 requested changes

2021-03-23 08:24 UTC, yonatandt commented on shared/malshab/malshab.interface.ts
> +    kaba?: number;
There is no need for it. We are not supposed to validate that. We trust our input completely.

2021-03-23 08:24 UTC, yonatandt commented on shared/malshab/malshab.interface.ts
> +    dapar?: number;
There is no need for it. We are not supposed to validate that. We trust our input completely.

2021-03-23 08:27 UTC, yonatandt commented on shared/malshab/malshab.interface.ts
> +export default interface Malshab {
That is not true. The default export doesn't have to be the only exported value, it's just the default one.

2021-03-23 08:32 UTC, yonatandt commented on shared/malshab/malshab.interface.ts
> +    gender?: number;
Good luck putting all the genders in an enum 😉

2021-03-23 08:46 UTC, yonatandt commented on shared/mongoose.ts
> +        });
Why should we?
It can work without it.

2021-03-24 09:17 UTC, AdarPascal commented on shared/event/event.interface.ts
> +export interface Event {
Not a global interface naming convention standard. Only Yesodot's habit.

2021-03-24 09:25 UTC, AdarPascal approved these changes

2021-03-24 09:30 UTC, yonatandt commented on shared/event/event.interface.ts
> +export interface Event {
That's not only a Yesodot's standard. In C# for example, interfaces usually have an `I` prefix.
But it seems that most developers tend not to use it, as in [this](https://stackoverflow.com/questions/2814805/java-interfaces-implementation-naming-convention) [this](https://stackoverflow.com/questions/541912/interface-naming-in-java) and [this](https://softwareengineering.stackexchange.com/questions/117348/should-interface-names-begin-with-an-i-prefix).

2021-03-24 15:55 UTC, lustigy96 requested changes

2021-03-24 15:55 UTC, lustigy96 commented on shared/malshab/malshab.interface.ts
> +
I think there should be an enum of Gender (and not type) because it is clearer.

2021-03-25 14:13 UTC, carmeltsadok approved these changes

2021-03-29 10:39 UTC, carmeltsadok commented on shared/error/error.ts
> +        if (!message) {
The message is required, so it will never go there.

2021-03-29 10:43 UTC, carmeltsadok requested changes

2021-03-29 10:43 UTC, carmeltsadok commented on shared/unit/unit.interface.ts
> +    id: string;
For type validation, id shouldn't exist
```suggestion
```

2021-03-29 10:43 UTC, carmeltsadok commented on shared/unit/unit.model.ts
> +    },
For type validation, id shouldn't exist
```suggestion
```

2021-03-29 10:47 UTC, carmeltsadok requested changes

2021-03-29 10:47 UTC, carmeltsadok commented on shared/unit/unit.model.ts
> +    },
```suggestion
    name: {
        type: String,
        unique: true,
        required: true,
        index: true,
    },
```

2021-03-29 11:36 UTC, carmeltsadok requested changes

2021-03-29 11:36 UTC, carmeltsadok commented on shared/mongoose.ts
> +dbInstance.on('connecting', () => {
There is a bug when connecting. dbInstance is undefined

2021-03-29 12:01 UTC, maykremer requested changes

2021-03-29 13:33 UTC, carmeltsadok commented on shared/authWrapper.ts
> +    return null;
```suggestion
    let formattedUser = null;
    jwt.verify(token, config.auth.secret, (err, decoded) => {
        if (err) {
            // later, log error
        }
        formattedUser = formatUserFromToken(decoded);
    });
    return formattedUser;
```

2021-03-29 13:33 UTC, carmeltsadok commented on shared/authWrapper.ts
> +    };
```suggestion
        if (header && header.split(' ')[1]) {
            const user = handleUserToken(header.split(' ')[1]);
            if (user) {
                await func(context, req, user);
            } else {
                context.res = {
                    status: 401,
                };
            }
        } else {
            context.res = {
                status: 401,
            };
        }
```

2021-03-30 09:55 UTC, maykremer commented on shared/nodesGroup/nodeGroups.interface.ts
> +    id: string;
nodes group interface should be:
    id: string;
    name: string;
    unitId: string;
    usersIds: string[];
    nodesIds: string[];

2021-03-30 10:01 UTC, maykremer commented on shared/nodesGroup/nodesGroup.interface.ts
> +}
Nodes group interface should include : nodesIds: string[];

2021-03-30 10:05 UTC, maykremer commented on shared/nodesGroup/nodesGroup.model.ts
> +    ],
Nodes group model should also include :
  nodesIds: [
        {
            type: String,
            ref: collectionNames.node,
        },
    ],

2021-03-30 15:34 UTC, lustigy96 commented on shared/node/node.model.ts
> +    nodeGroupId: {
```suggestion
    nodesGroupId: {
```

spelling according to the interface

2021-03-30 15:47 UTC, lustigy96 requested changes

2021-03-30 15:47 UTC, lustigy96 commented on shared/node/node.model.ts
> +// TODO: <unitId,name> should be unique.
why unitId should  be unique? the might be multiple nodes per unit

2021-04-01 10:42 UTC, maykremer commented on shared/nodesGroup/nodesGroup.interface.ts
> +    usersIds: string[];
usersIds type should be array of objectId.

2021-04-04 06:22 UTC, yonatandt commented on shared/nodesGroup/nodesGroup.interface.ts
> +    usersIds: string[];
I think that string should be enough for our dedicated use.
Why do you believe that `string` is not enough?

2021-04-04 06:25 UTC, yonatandt commented on shared/node/node.interface.ts
> +export interface Node {
We have decided to not use the `I` prefix in an interface's name.

2021-04-04 06:30 UTC, yonatandt commented on shared/user/user.model.ts
> +        ref: collectionNames.unit,
A user cannot be in more than one unit. But there are users that don't even have a unit, like a technical user.

2021-04-04 06:32 UTC, yonatandt commented on shared/malshab/malshab.interface.ts
> +
I truly believe there is no reason to. Either way, we get that as an input without validation.

2021-04-04 06:36 UTC, yonatandt commented on shared/error/error.ts
> +        if (!message) {
message can be falsy (undefined or an empty string)

2021-04-04 06:38 UTC, yonatandt commented on shared/unit/unit.interface.ts
> +    id: string;
Why should it be that way?

2021-04-04 07:03 UTC, yonatandt commented on shared/event/event.interface.ts
> +}
It is not in the excalidraw.

2021-04-04 07:06 UTC, yonatandt commented on shared/event/event.model.ts
> +            type: Schema.Types.ObjectId,
Its a refernce to the node, therefore it should be an objectId.

2021-04-04 07:06 UTC, yonatandt commented on shared/event/event.model.ts
> +            type: Schema.Types.ObjectId,
Its a refernce to the malshab, therefore it should be an objectId.

2021-04-04 07:40 UTC, yonatandt commented on shared/node/node.model.ts
> +// TODO: <unitId,name> should be unique.
The couple `<unitId, name>` together should be unique

2021-04-04 07:42 UTC, yonatandt commented on shared/nodesGroup/nodesGroup.interface.ts
> +}
The node already includes an `nodesGroupId`

2021-04-04 07:42 UTC, yonatandt commented on shared/nodesGroup/nodesGroup.model.ts
> +    ],
The node already includes an `nodesGroupId`

2021-04-05 08:06 UTC, carmeltsadok requested changes

2021-04-05 08:06 UTC, carmeltsadok commented on shared/unit/unit.interface.ts
> +}
```suggestion
export default interface Unit {
    _id?: string,
    name: string;
}
```

2021-04-05 08:34 UTC, maykremer requested changes

2021-04-05 08:34 UTC, maykremer commented on shared/authWrapper.ts
> +        const header = req.headers.Authorization;
```suggestion
        const header = req.headers.authorization;
```

2021-04-05 08:52 UTC, carmeltsadok submitted a review, later dismissed

2021-04-05 09:36 UTC, maykremer approved these changes

2021-04-05 12:12 UTC, lustigy96 approved these changes

2021-04-05 12:23 UTC, merged