Function/get malshab
alphayesodot/itur-be-functionapp pull request #25
Opened 2021-03-30 21:52 UTC by lustigy96

2021-04-18 10:42 UTC, yonatandt requested changes

2021-04-18 10:42 UTC, yonatandt commented on GetMalshab/index.ts
> +        } else {
redundant `else`

2021-04-18 10:42 UTC, yonatandt commented on GetMalshab/index.ts
> +            const malshab = await MalshabModel.find({ identityNumber: identityNumber }).exec();
```suggestion
            const malshab = await MalshabModel.find({ identityNumber }).exec();
```

2021-04-18 10:42 UTC, yonatandt commented on GetMalshab/utils.ts
> +    return undefined;
```suggestion
    return (Object.keys(filtered).length) ? filtered : undefined;
```

2021-04-18 10:42 UTC, yonatandt commented on GetMalshab/permissions.ts
> +const rolePermissions = {
Not that good of a name,
Maybe call it `malshabFieldsByRole`.

2021-04-18 10:42 UTC, yonatandt commented on GetMalshab/utils.ts
> +export const malshabFilter = (malshab: Malshab & mongoose.Document<any>, allowedKeys: string[]): Partial<Malshab> | undefined => {
Add documentation for this function.

2021-04-18 10:42 UTC, yonatandt commented on GetMalshab/utils.ts
> +export const getPermissions = (role: Role): string[] => {
Add documentation for this function.
Also, consider changing the name to: `getAllowedMalshabFields`, or something better.

2021-04-18 13:02 UTC, carmeltsadok requested changes

2021-04-18 13:07 UTC, yonatandt commented on GetMalshab/index.ts
> +            const malshab = await MalshabModel.find({ identityNumber: identityNumber }).exec();
Also, consider using `findOne` instead.

2021-04-19 07:19 UTC, yonatandt requested changes

2021-04-19 07:19 UTC, yonatandt commented on GetMalshab/index.ts
> +        const malshab = await MalshabModel.find({ identityNumber }).exec();
Use `findOne` instead of `find`.

2021-04-19 13:19 UTC, yonatandt approved these changes

2021-04-19 13:22 UTC, carmeltsadok approved these changes

2021-04-19 13:35 UTC, yonatandt approved these changes

2021-04-19 13:35 UTC, merged