Get node functions
alphayesodot/itur-be-functionapp pull request #26
Opened 2021-03-31 10:05 UTC by lustigy96

2021-04-18 12:49 UTC, carmeltsadok requested changes

2021-04-18 12:49 UTC, carmeltsadok commented on .gitignore
> +mock.ts
```suggestion
```

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeById/function.json
> +  "scriptFile": "../dist/getNodeById/index.js"
```suggestion
  "scriptFile": "../dist/GetNodeById/index.js"
```

Change folder's name as well. (To do so, commit twice- one without the folder, and one with the uppercase name)

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeById/index.ts
> +const getNodeById: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const getNodeById: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeById/index.ts
> +        const nodeId = req.params.id; // is validation of id requried?
Remove message or add joi schema validation

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeById/index.ts
> +            throw new ValidationFunctionError(functionName, `user id or user role is not spesfied`);
```suggestion
            throw new ValidationFunctionError(functionName, `User id or user role is not specified`);
```

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeById/index.ts
> +            throw new ValidationFunctionError(functionName, `user id or user role is not spesfied`);
There is no need for role checking, you are going to check it in the next condition.

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeById/index.ts
> +        const nodes: Node[] = await NodeModel.find({ id: nodeId });
Change to find by id, and then there will be only one result, and you won't be need to reach the first element in the array `nodes[0]`

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeByUnit/function.json
> +  "scriptFile": "../dist/getNodeByUnit/index.js"
```suggestion
  "scriptFile": "../dist/GetNodeByUnit/index.js"
```
Change directory's name as well like the previous.

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +const getNodeByUnit: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const getNodeByUnit: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```

2021-04-18 12:49 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +    const unitId = req.query.unitId;
You can add joi validation schema

2021-04-18 12:59 UTC, carmeltsadok requested changes

2021-04-18 12:59 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +        user.role === Role.RamadIturAssistant || user.role === Role.RamadIturOfUnit ? user.unitId : unitId === '' ? undefined : unitId;
The embedded conditional (ternary) operator is less readable.

2021-04-18 12:59 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +            if (user.unitId === undefined || user.unitId === '') {
```suggestion
            if (!user.unitId) {
```

2021-04-18 12:59 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +    }
Move it to the top

2021-04-18 13:40 UTC, yonatandt requested changes

2021-04-18 13:40 UTC, yonatandt commented on getNodeById/index.ts
> +        const nodeId = req.params.id; // is validation of id requried?
I think we don't have to validate that.

2021-04-19 07:02 UTC, carmeltsadok commented on getNodeById/function.json
> +  "scriptFile": "../dist/getNodeById/index.js"
You need to change folders names as well (you can see that in the git files the name is not updated)

2021-04-19 07:15 UTC, carmeltsadok commented on getNodeByUnit/function.json
> +  "scriptFile": "../dist/getNodeByUnit/index.js"
You need to change folders names as well (you can see that in the git files the name is not updated)

2021-04-19 07:16 UTC, carmeltsadok commented on getNodeById/index.ts
> +        const nodes: Node[] = await NodeModel.find({ id: nodeId });
Change to find one

2021-04-19 07:32 UTC, carmeltsadok requested changes

2021-04-19 07:32 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +        const searchingFilter: any = { unitId: unitIdToSearch };
```suggestion
        const searchingFilter: any = { unitId: unitIdToSearch, nodeGroupId: nodeGroupIdToSearch };
```
When the role is `RamadIturAssistant`, The `nodeGroupId` won't be included in the filter.

2021-04-19 07:32 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +                }
```suggestion
```

2021-04-19 07:32 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +                }
```suggestion
```

2021-04-19 07:32 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +        const nodesGroupId = req.query.nodesGroupId;
```suggestion
        const nodeGroupId = req.query.nodeGroupId;
```

2021-04-19 07:32 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +        const nodesGroupIdToSearch = nodesGroupId === '' ? undefined : nodesGroupId;
```suggestion
        const nodeGroupIdToSearch = nodeGroupId === '' ? undefined : nodeGroupId;
```

2021-04-19 07:36 UTC, yonatandt requested changes

2021-04-19 07:36 UTC, yonatandt commented on GetUnitById/index.ts
> +const getUnitById: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
Why though?
It is not relevant to the PR and also we put the `_` prefix only on function parameters we do not use.

2021-04-19 07:36 UTC, yonatandt commented on getNodeById/function.json
> +  "scriptFile": "../dist/GetNodeById/index.js"
Don't forget to change the folder name as well

2021-04-19 07:36 UTC, yonatandt commented on getNodeById/index.ts
> +            throw new ValidationFunctionError(functionName, `User id is not specified`);
```suggestion
            throw new ValidationFunctionError(functionName, `Node id is not specified`);
```

2021-04-19 07:36 UTC, yonatandt commented on getNodeByUnit/index.ts
> +        const nodesGroupId = req.query.nodesGroupId;
It's `nodeGroup` now, not `nodesGroup` 😃

2021-04-19 07:36 UTC, yonatandt commented on getNodeByUnit/index.ts
> +const getNodeByUnit: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
Let's sit on this function together @lustigy96

2021-04-19 07:38 UTC, carmeltsadok requested changes

2021-04-19 07:38 UTC, carmeltsadok commented on getNodeByUnit/index.ts
> +        const unitId = req.query.unitId;
```suggestion
        const { unitId } = req.query;
```

2021-04-19 13:33 UTC, yonatandt requested changes

2021-04-19 13:33 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +        if (nodeGroupId !== undefined) {
```suggestion
        if (!nodeGroupId) {
```

2021-04-19 13:33 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +            searchingFilter.nodeGroupId = nodeGroupIdToSearch;
```suggestion
            searchingFilter.nodeGroupId = nodeGroupId;
```

2021-04-19 13:33 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +        const nodeGroupIdToSearch = nodeGroupId === '' ? undefined : nodeGroupId;
Unnecessary

2021-04-19 13:33 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +                    throw new ValidationFunctionError(functionName, 'unit id is not specified');
Unit ID is optional for Technical users

2021-04-19 13:33 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +            case Role.Itur:
So what are these users able to do? Are they like the Technical user or Ramad Itur here? @yubbi99 
It is not specified in the API sheet.

2021-04-19 13:33 UTC, yonatandt commented on GetUnitById/index.ts
> +const getUnitById: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
?

2021-04-19 13:33 UTC, yonatandt commented on shared/node/node.model.ts
> +nodeSchema.index({ id: 1, name: 1, unitId: 1 }, { unique: true, sparse: true });
Id is unique by itself, so there is no need to add it here.
The question is if the pair <name,unitId> should be unique, i.e. a unit will not have 2 nodes with the same name.
@yubbi99

2021-04-20 07:30 UTC, yonatandt requested changes

2021-04-20 07:30 UTC, yonatandt commented on GetNodeById/index.ts
> +        }
It is really redundant to check that. There is no reason to.

2021-04-20 07:30 UTC, yonatandt commented on GetNodeById/index.ts
> +        }
And its `Node` not `User`

2021-04-20 07:30 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +                    throw new ValidationFunctionError(functionName, 'ramad itur assistant must specify nodesGroup Id');
```suggestion
                    throw new ValidationFunctionError(functionName, 'ramad itur assistant must specify nodeGroup Id');
```

2021-04-20 10:13 UTC, lustigy96 commented on GetUnitById/index.ts
> +const getUnitById: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
didn't know that :P

2021-04-20 10:15 UTC, lustigy96 commented on GetUnitById/index.ts
> +const getUnitById: AzureFunction = async (_context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
in a mistake

2021-04-20 10:17 UTC, lustigy96 commented on GetNodeByUnit/index.ts
> +        if (nodeGroupId !== undefined) {
not really, because it maybe an empty string but not undefined

2021-04-20 10:18 UTC, lustigy96 commented on GetNodeByUnit/index.ts
> +            searchingFilter.nodeGroupId = nodeGroupIdToSearch;
not really, because Im taking care of the case when nodeGroupId is an empty string (using the nodeGroupIdToSearch)

2021-04-20 10:20 UTC, lustigy96 commented on GetNodeByUnit/index.ts
> +        const nodeGroupIdToSearch = nodeGroupId === '' ? undefined : nodeGroupId;
necessary 
simce using find with {nodeGroupId : ''} is nor the same as  {nodeGroupId : undefined}

2021-04-20 10:21 UTC, lustigy96 commented on GetNodeByUnit/index.ts
> +                    throw new ValidationFunctionError(functionName, 'unit id is not specified');
But they cant get node by unit without a unit. Each node has a unit isn't it ?

2021-04-20 10:23 UTC, lustigy96 commented on GetNodeByUnit/index.ts
> +                    throw new ValidationFunctionError(functionName, 'ramad itur assistant must specify nodesGroup Id');
This is outdated because I changed it yesterday ..

2021-04-20 10:30 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +        if (nodeGroupId !== undefined) {
OK. Please add an explanation.

2021-04-20 12:00 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +        const { nodesGroupId } = req.query;
```suggestion
        const { nodeGroupId } = req.query;
```

2021-04-20 12:00 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +                if (!nodesGroupId) {
```suggestion
                if (!nodeGroupId) {
```

2021-04-20 12:02 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +        if (nodesGroupId !== undefined) {
```suggestion
        if (nodeGroupId !== undefined) {
```

2021-04-20 12:03 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +            searchingFilter.nodesGroupId = fieldAdjusmentToSearch(nodesGroupId);
```suggestion
            searchingFilter.nodeGroupId = fieldAdjusmentToSearch(nodeGroupId);
```

2021-04-20 12:30 UTC, yonatandt approved these changes

2021-04-20 14:25 UTC, carmeltsadok approved these changes

2021-04-20 14:26 UTC, merged