feat: getUser function
alphayesodot/itur-be-functionapp pull request #27
Opened 2021-04-06 06:49 UTC by yonatandt

Signed-off-by: YonatanTal <yonatald@gmail.com>

2021-04-19 12:08 UTC, carmeltsadok requested changes

2021-04-19 12:08 UTC, carmeltsadok commented on GetUserById/function.json
> +      "name": "req",
```suggestion
      "name": "getUserById",
```

2021-04-19 12:08 UTC, carmeltsadok commented on GetUserById/index.ts
> +        const user = await userModel.find({ _id: userId, ...additionalFilter });
```suggestion
        const user = await userModel.findOne({ _id: userId, ...additionalFilter });

```

2021-04-19 13:41 UTC, carmeltsadok approved these changes

2021-04-20 08:00 UTC, lustigy96 approved these changes

2021-04-20 08:03 UTC, merged