feat: CreateUser function
alphayesodot/itur-be-functionapp pull request #28
Opened 2021-04-06 06:52 UTC by yonatandt

Signed-off-by: YonatanTal <yonatald@gmail.com>

2021-04-18 13:11 UTC, carmeltsadok requested changes

2021-04-18 13:11 UTC, carmeltsadok commented on createUser/function.json
> +  "scriptFile": "../dist/createUser/index.js"
```suggestion
  "scriptFile": "../dist/CreateUser/index.js"
```
Change folder's name as well. (To do so, commit twice- one without the folder, and one with the uppercase name)

2021-04-18 13:11 UTC, carmeltsadok commented on createUser/readme.md
> +# QueueTrigger - TypeScript
Remove this file

2021-04-20 11:33 UTC, carmeltsadok approved these changes

2021-04-20 11:46 UTC, lustigy96 requested changes

2021-04-20 11:46 UTC, lustigy96 commented on CreateUser/index.ts
> +        context.log.error(err + context.invocationId);
why do we need this context.log ? 
Don't think it suppose to be in the dev version

2021-04-20 11:50 UTC, yonatandt commented on CreateUser/index.ts
> +        context.log.error(err + context.invocationId);
We still did not decide on how to handle our logs, so in the meantime, I just use `contet.log`.

2021-04-20 11:58 UTC, lustigy96 approved these changes

2021-04-20 12:03 UTC, merged