fix: Fix event interface
alphayesodot/itur-be-functionapp pull request #34
Opened 2021-04-22 06:23 UTC by carmeltsadok

2021-04-22 07:40 UTC, yonatandt approved these changes

2021-04-22 15:27 UTC, AdarPascal commented on shared/event/event.interface.ts
>      filesUrls: string[];
Change to "fileKeys" according to the attachment function design

2021-04-22 15:28 UTC, AdarPascal requested changes

2021-04-22 15:28 UTC, AdarPascal commented on shared/event/event.interface.ts
>      filesUrls: string[];
Change to "fileKeys" according to the attachment function design

2021-04-27 07:27 UTC, yonatandt requested changes

2021-04-27 07:27 UTC, yonatandt commented on shared/event/event.interface.ts
> +    isOccurred: boolean;
Didn't we say we don't need to save it, because we can assume it from the result? @yubbi99

2021-04-27 14:26 UTC, yonatandt submitted a review, later dismissed

2021-04-28 06:30 UTC, yonatandt approved these changes

2021-04-28 12:01 UTC, maykremer approved these changes

2021-05-02 12:48 UTC, closed without merging