Function/attachments
alphayesodot/itur-be-functionapp pull request #35
Opened 2021-04-22 13:12 UTC by AdarPascal

2021-04-25 10:58 UTC, yonatandt commented on AttachmentUpload/index.ts
> +// eslint-disable-next-line import/no-unresolved
I believe it is not needed anymore, I added it to the linter file.

2021-04-27 07:22 UTC, yonatandt submitted a review, later dismissed

2021-04-27 07:22 UTC, yonatandt commented on shared/utils/structure.ts
> +};
What happens if you have an array directly inside of an array?
Will it still work as expected?

2021-04-27 07:22 UTC, yonatandt commented on shared/utils/structure.ts
> +export const cleanObj = (obj: any) => {
The function also decodes its values, you should add it to the function documentation.

2021-04-27 07:22 UTC, yonatandt commented on shared/utils/structure.ts
> +    return Object.prototype.toString.call(v) === '[object Object]';
There is a more correct way to check if a property is an object.
You can read about it [here](https://stackoverflow.com/questions/8511281/check-if-a-value-is-an-object-in-javascript/8511350#8511350).

2021-04-27 07:22 UTC, yonatandt commented on shared/utils/structure.ts
> +};
Add documentation for those functions.

2021-04-27 07:22 UTC, yonatandt commented on shared/utils/structure.ts
> +};
Where do you use this function?

2021-04-27 07:22 UTC, yonatandt commented on shared/utils/structure.ts
> +};
I don't see you use this function at all.

2021-04-28 04:03 UTC, AdarPascal commented on shared/utils/structure.ts
> +};
Yes

2021-04-28 04:03 UTC, AdarPascal commented on shared/utils/structure.ts
> +export const cleanObj = (obj: any) => {
Belongs to the xml processor branch. Probably a mistake.
Deleting it for now.

2021-04-28 06:46 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +                break;
This could change the functionality of this code.
If this fallthrough is intended, you should add a `falls through` comment right before the next `case`.
You can read more about it [here](https://eslint.org/docs/rules/no-fallthrough).

2021-04-28 06:47 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +                break;
@lustigy96 make sure you solve it together.

2021-04-28 06:48 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +/* eslint-disable no-case-declarations */
If you still want to keep it, please add it to the linter.
Otherwise, make sure @lustigy96 solves this.

2021-04-28 06:59 UTC, yonatandt commented on config.ts
> +        MALSHAB_QUEUE_NAME: env.get('MALSHAB_QUEUE_NAME').required().asString(),
So if we decide that Azure resources should be taken from environment variables, then we should also make sure all the other written functions are falling into line @carmeltsadok.

About whether it should be in the `attachment` object: because this queue has other purposes than to send attachments to, it should be in a different object, like maybe under `queues` / `azure.resources` /  `malshab`.
Please decide on a standard @carmeltsadok.

2021-04-28 07:05 UTC, yonatandt commented on GetAttachmentByKey/index.ts
> +            throw new CustomFunctionError(
Why not using  `ForbiddenFunctionError`?

2021-04-28 07:25 UTC, yonatandt commented on AttachmentUpload/index.ts
> +        }
Now, after you've changed the route you don't need this validation because there is no reason to get the malshabId from the query.

2021-04-28 07:27 UTC, yonatandt commented on AttachmentUpload/function.json
> +      "route": "malshab/:id/attachment"
```suggestion
      "route": "malshab/{malshabId}/attachment"
```

2021-04-28 07:27 UTC, yonatandt commented on AttachmentUpload/index.ts
> +                    identityNumber: req.query.identityNumber,
```suggestion
                    identityNumber: req.params.malshabId,
```

2021-04-28 07:28 UTC, carmeltsadok commented on config.ts
> +        MALSHAB_QUEUE_NAME: env.get('MALSHAB_QUEUE_NAME').required().asString(),
I think we should put it in `azure.resources`.

2021-04-28 07:32 UTC, yonatandt commented on shared/file/file.interface.ts
> +}
Is it in use?

2021-04-28 07:55 UTC, yonatandt commented on AttachmentUpload/index.ts
> +                    attachments: decodedFilekey,
Should be in an array, because the attachments in the malshab are an array of strings.

2021-04-28 11:32 UTC, AdarPascal commented on shared/file/file.interface.ts
> +}
Yes, in `blob.tools.ts`

2021-04-28 11:35 UTC, AdarPascal commented on GetAttachmentByKey/index.ts
> +            throw new CustomFunctionError(
`ForbiddenFunctionError` doesn't provide the use of a custom error string which i needed in this function.
I think that it is a good idea to be able to throw an error with a custom error status and error description, and also get all of the error class benefits.

2021-04-28 12:14 UTC, AdarPascal commented on AttachmentUpload/index.ts
> +        }
Nice. Deleting this validation.

2021-04-28 12:17 UTC, AdarPascal commented on AttachmentUpload/index.ts
> +                    attachments: decodedFilekey,
Changing

2021-04-28 12:27 UTC, AdarPascal commented on GetNodeByUnit/index.ts
> +/* eslint-disable no-case-declarations */
Me and @lustigy96 solved this.

2021-04-28 12:27 UTC, AdarPascal commented on GetNodeByUnit/index.ts
> +                break;
Me and @lustigy96 solved this.

2021-04-28 12:34 UTC, AdarPascal commented on GetMalshab/utils.ts
> +    // eslint-disable-next-line no-prototype-builtins
Me and @lustigy96 changed the function follows to linter good js right-use corrections.

2021-04-29 06:23 UTC, yonatandt commented on GetAttachmentByKey/index.ts
> +            throw new CustomFunctionError(
Then you can add an `info` or `additionalInfo` optional param to the  `ForbiddenFunctionError` class, and send it there.

2021-04-29 06:25 UTC, yonatandt commented on GetNodeByUnit/index.ts
> +            // eslint-disable-next-line no-fallthrough
```suggestion
            // fallthrough
```

2021-04-29 16:43 UTC, AdarPascal commented on GetAttachmentByKey/index.ts
> +            throw new CustomFunctionError(
Nice

2021-06-28 12:02 UTC, carmeltsadok requested changes

2021-06-28 12:02 UTC, carmeltsadok commented on shared/malshab/malshab.permissions.ts
> +const canAccessMalshabAttachments = async (functionName: string, user: User, malshabId: string) => {
isn't it should be in the `GetAttachmentByKey` folder?

2021-06-28 19:53 UTC, AdarPascal commented on AttachmentUpload/index.ts
> +            });
Yes because if there is an error, I dont wanna throw the error, instead I wanna throw my custom error

2021-06-28 19:55 UTC, AdarPascal commented on shared/malshab/malshab.permissions.ts
> +const canAccessMalshabAttachments = async (functionName: string, user: User, malshabId: string) => {
You specifically asked me before writing this permission check to put it in a shared folder so it will be available to all of the functions.
Please be a bit more decisive.

2021-06-29 04:13 UTC, carmeltsadok commented on shared/malshab/malshab.permissions.ts
> +const canAccessMalshabAttachments = async (functionName: string, user: User, malshabId: string) => {
When?

2021-06-29 04:21 UTC, carmeltsadok requested changes

2021-06-29 04:21 UTC, carmeltsadok commented on shared/malshab/malshab.permissions.ts
> +const canAccessMalshabAttachments = async (functionName: string, user: User, malshabId: string) => {
The way it is written looks like a specific validation for the attachments function only. If we would like to put it in the shared file, there is a need to open an ‘malshab.manager.ts’ file and put it there with a more generic name.

2021-06-29 12:15 UTC, carmeltsadok approved these changes

2021-06-29 20:46 UTC, maykremer approved these changes

2021-06-29 21:48 UTC, merged