Function/get malshab
alphayesodot/itur-be-functionapp pull request #40
Opened 2021-05-06 08:00 UTC by lustigy96

Fix role limitations

2021-05-09 07:42 UTC, yonatandt requested changes

2021-05-09 15:10 UTC, carmeltsadok requested changes

2021-05-09 15:10 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                    'malshabShort.id': identityNumber,
```suggestion
                    'malshabShort.identityNumber': identityNumber,
```

2021-05-09 15:10 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                if (!unitsOfMalshabEvents || !unitsOfMalshabEvents.includes(user.unitId)) {
if `unitsOfMalshabEvents` is false, wouldn't be an error when you are trying to run `includes` on it?

2021-05-09 16:07 UTC, lustigy96 commented on GetMalshab/index.ts
> +                    throw new ValidationFunctionError(functionName, `The malshab has no interview today with interviewer ${user.id}.`);
change to forbidden.

2021-05-09 16:09 UTC, lustigy96 commented on GetMalshab/index.ts
> +                if (!unitsOfMalshabEvents || !unitsOfMalshabEvents.includes(user.unitId)) {
if unitsOfMalshabEvents is false, so the condition is true on the first check, and another condition won't be checked...

2021-05-11 06:51 UTC, carmeltsadok requested changes

2021-05-11 06:51 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                const event: Event[] = await EventModel.find({
```suggestion
                const events: Event[] = await EventModel.find({
```

2021-05-12 07:24 UTC, carmeltsadok submitted a review, later dismissed

2021-05-13 15:43 UTC, carmeltsadok requested changes

2021-05-13 15:43 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                break;
```suggestion
            case Role.Mada:
            case Role.Itur:
            case Role.Technical:
                break;
```

2021-05-13 15:43 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                    throw new ObjectNotFoundFunctionError(functionName, 'malshab', identityNumber);
It is supposed to be a validation error (The interviewer can't get malshab's info because he doesn't have events that day with him.

2021-05-13 15:43 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                    nodeIdsOfMalshabEvents.length &&
can't `nodeIdsOfMalshabEvents` be undefined? ( in case `malshabEvents` is undefined)

2021-05-13 15:43 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                    nodeIdsOfMalshabEvents.length &&
anyway, even if the array is empty, you can still run the `find` query.

2021-05-13 15:43 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                    const unitsOfMalshabEvents = populatedNodesOfMalshabEvents && populatedNodesOfMalshabEvents.map((node) => node.unitId.toString());
```suggestion
                    const unitsOfMalshabEvents = populatedNodesOfMalshabEvents?.map((node) => node.unitId.toString());
```

2021-05-13 15:43 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                            .map((node) => {
```suggestion
                        populatedNodesOfMalshabEvents?
                            .map((node) => {
```

2021-05-13 15:43 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                    if (!usersOfNodeGroups.includes(user.id)) {
```suggestion
                    if (!usersOfNodeGroups || !usersOfNodeGroups.includes(user.id)) {
```

2021-05-13 15:43 UTC, carmeltsadok commented on config.ts
> +            nodeGroup: 'nodegroup',
```suggestion
            nodeGroup: 'NodeGroup',
```

2021-05-13 15:49 UTC, lustigy96 commented on GetMalshab/index.ts
> +                    throw new ObjectNotFoundFunctionError(functionName, 'malshab', identityNumber);
I think I talked with Yonathan about it... and this one is better

2021-05-13 15:51 UTC, lustigy96 commented on GetMalshab/index.ts
> +                    nodeIdsOfMalshabEvents.length &&
why should I do that... if it is empty it is better to save this db query,  it's a waist of time. (calling a db take a lot of time) 
and nodeIdsOfMalshabEvents cannot be undefined :)

2021-05-13 15:55 UTC, carmeltsadok commented on GetMalshab/index.ts
> +                    nodeIdsOfMalshabEvents.length &&
you wrote `malshabEvents?` so if there are no malshabEvents it will be undefined

2021-05-18 07:16 UTC, lustigy96 commented on GetMalshab/index.ts
> +                    nodeIdsOfMalshabEvents.length &&
It will be empty ...

2021-05-20 14:01 UTC, carmeltsadok submitted a review, later dismissed

2021-05-23 14:30 UTC, yonatandt requested changes

2021-05-23 14:30 UTC, yonatandt commented on GetMalshab/index.ts
> +                endOfToday.setHours(23, 59, 59, 999);
It would be better to put it in a function outside (in the shared folder)

2021-05-23 14:30 UTC, yonatandt commented on GetMalshab/index.ts
> +                }
IMO you should put it inside a separate function/s (with documentation).

2021-05-27 11:33 UTC, yonatandt approved these changes

2021-05-27 12:30 UTC, carmeltsadok submitted a review, later dismissed

2021-05-30 14:51 UTC, carmeltsadok approved these changes

2021-05-31 07:56 UTC, yonatandt approved these changes

2021-05-31 11:40 UTC, merged