Feat/questionnaire schema
alphayesodot/itur-be-functionapp pull request #50
Opened 2021-05-24 12:38 UTC by carmeltsadok

2021-05-24 17:18 UTC, lustigy96 requested changes

2021-05-24 17:18 UTC, lustigy96 commented on AddNodeToQuestionnaireSchema/index.ts
> +import authWrapper from '../shared/authWrapper';
```suggestion
import { authWrapper } from '../shared/authWrapper';
```

2021-05-24 17:18 UTC, lustigy96 commented on AddNodeToQuestionnaireSchema/index.ts
> +            throw new ObjectNotFoundFunctionError(functionName, 'questionnaire schema', schemaId);
```suggestion
            throw new ObjectNotFoundFunctionError(functionName, 'questionnaireSchema', schemaId);
```

2021-05-24 17:18 UTC, lustigy96 commented on AddNodeToQuestionnaireSchema/index.ts
> +import authWrapper from '../shared/authWrapper';
I suggest you do a pull from questionnaire again, and check that everything really works (with the changes we did)

2021-05-24 17:18 UTC, lustigy96 commented on DeleteQuestionnaireSchema/index.ts
> +            throw new ObjectNotFoundFunctionError(functionName, 'questionnaire schema', questionnaireSchemaId);
isn't it the name of the object? just like we write nodeGroup and not node group....

2021-05-24 17:18 UTC, lustigy96 commented on RemoveNodeFromQuestionnaireSchema/function.json
> +{
I think the name of the function should be deteleNodeFromSchema and not remove... 
Since you use a delete request and all of out delete requests starts with delete and not remove 
(and yes, I think the same of 'RemoveUserFromNodeGroup'... It is easer to follow the folder this way.. ) Don't you think too?

2021-05-24 17:18 UTC, lustigy96 commented on RemoveNodeFromQuestionnaireSchema/index.ts
> +import authWrapper from '../shared/authWrapper';
```suggestion
import { authWrapper } from '../shared/authWrapper';
```

2021-05-24 17:18 UTC, lustigy96 commented on RemoveNodeFromQuestionnaireSchema/index.ts
> +import authWrapper from '../shared/authWrapper';
again, suggest to pull from questionnaire

2021-05-24 17:18 UTC, lustigy96 commented on shared/authWrapper.ts
> +    return undefined;
isn't it undefined anyway?

2021-05-25 08:47 UTC, carmeltsadok commented on shared/authWrapper.ts
> +    return undefined;
We need to return a value

2021-05-25 08:48 UTC, carmeltsadok commented on RemoveNodeFromQuestionnaireSchema/function.json
> +{
I think it is fine because we remove an item from an array.

2021-05-25 09:52 UTC, lustigy96 commented on shared/authWrapper.ts
> +    return undefined;
eslint ?

2021-05-25 10:42 UTC, lustigy96 approved these changes

2021-05-25 10:43 UTC, merged