Functions/questionnaire instance
alphayesodot/itur-be-functionapp pull request #56
Opened 2021-05-30 07:40 UTC by lustigy96

2021-05-31 12:44 UTC, carmeltsadok requested changes

2021-05-31 12:44 UTC, carmeltsadok commented on CreateQuestionnaireInstance/index.ts
> + * Malshab gets forbbiden, and user gets validation
```suggestion
 * This function alternate between errors according to the requester type.
 * We need it since we don't want to show the malshab the reason for the error.
 * Malshab gets forbidden, and the user gets validation
```

2021-05-31 12:44 UTC, carmeltsadok commented on CreateQuestionnaireInstance/index.ts
> + * @returns
explain

2021-05-31 12:44 UTC, carmeltsadok commented on CreateQuestionnaireInstance/index.ts
> +const allowUniqeQuestionnaireInstanceInEvent = async (requesterType, requesterId, questionnaireSchema, event) => {
change to `allowUniqueQuestionnaireInstanceInEvent`

2021-05-31 12:44 UTC, carmeltsadok commented on CreateQuestionnaireInstance/index.ts
> + * @param userMessege - messege for a user
```suggestion
 * @param errorToUser- message for a user
```

2021-05-31 12:44 UTC, carmeltsadok commented on CreateQuestionnaireInstance/index.ts
> +    if (solvedQuestionnairesOfRequesterInEvent.length > 0) {
```suggestion
    if (solvedQuestionnairesOfRequesterInEvent.length) {
```

2021-05-31 12:44 UTC, carmeltsadok commented on shared/question/question.ts
> +const validateQuestions = (questions: any[], answerValidation: boolean) => {
why

2021-05-31 12:44 UTC, carmeltsadok commented on GetQuestionnaireInstanceById/index.ts
> +        // more validations? (I think the API is incorrect so check that the validations I did are good)
```suggestion
```

2021-05-31 12:44 UTC, carmeltsadok commented on GetQuestionnaireInstanceById/index.ts
> +                if (user.role === Role.RamadIturAssistant || user.role === Role.ProfessionalRamad) {
Separate to another case

2021-05-31 12:44 UTC, carmeltsadok commented on GetQuestionnaireInstanceById/index.ts
> +                }
if its `RamadIturAssistant ` or `ProfessionalRamad` it is enough to check the nodeGroup only, so separate to different cases

2021-05-31 13:24 UTC, carmeltsadok requested changes

2021-05-31 13:24 UTC, carmeltsadok commented on shared/error/error.ts
> +            status: 403,
```suggestion
            status: 400,
```

2021-05-31 14:32 UTC, lustigy96 commented on shared/question/question.ts
> +const validateQuestions = (questions: any[], answerValidation: boolean) => {
just ake a bug, I don't remember which. and we check for the length anyway.

2021-06-01 07:15 UTC, carmeltsadok commented on GetQuestionnaireInstanceById/index.ts
> +        // more validations? (I think the API is incorrect so check that the validations I did are good)
I think it is fine

2021-06-01 11:10 UTC, carmeltsadok approved these changes

2021-06-01 12:36 UTC, merged