Function/get questionnaire schema
alphayesodot/itur-be-functionapp pull request #57
Opened 2021-05-30 14:36 UTC by carmeltsadok

2021-05-31 14:23 UTC, lustigy96 requested changes

2021-05-31 14:23 UTC, lustigy96 commented on GetQuestionnaireSchemas/index.ts
> +        }
NodeId is optional and not required (in the API)

2021-05-31 14:23 UTC, lustigy96 commented on GetQuestionnaireSchemas/index.ts
> +        } else {
I don't like the else - already wrote about it on the other file

2021-05-31 14:23 UTC, lustigy96 commented on GetQuestionnaireSchemas/index.ts
> +                );
Malshab should get a malshab-error

2021-05-31 14:23 UTC, lustigy96 commented on GetQuestionnaireSchemas/index.ts
> +                targetTypes: [Role.RamadIturAssistant, Role.RamadIturOfUnit, Role.ProfessionalRamad].includes(user.role) ? undefined : user.role,
Does it really work with that targetTypes: undefined? 
I am asking because targetTypes won't be undefined.. and as much as I remember it won't work..

2021-05-31 14:23 UTC, lustigy96 commented on GetQuestionnaireSchemas/index.ts
> +
if questionnaireSchemas  does not exist return object not found

2021-05-31 14:23 UTC, lustigy96 commented on GetQuestionnaireSchemas/index.ts
> +                targetTypes: [Role.RamadIturAssistant, Role.RamadIturOfUnit, Role.ProfessionalRamad].includes(user.role) ? undefined : user.role,
I think that MADA may get all schemas... Even if they are not on the targetTypes

2021-06-01 06:56 UTC, carmeltsadok commented on GetQuestionnaireSchemaById/index.ts
> +            if (!(await getTodaysEvents({ 'node.id': { $in: questionnaireSchema.nodes }, 'malshabShort.id': malshab.identityNumber })).length) {
I think it too. we need to make an overall change in the interface

2021-06-01 07:04 UTC, carmeltsadok commented on GetQuestionnaireSchemaById/index.ts
> +                    }
Why

2021-06-01 07:04 UTC, carmeltsadok commented on GetQuestionnaireSchemaById/index.ts
> +            }
Why

2021-06-01 07:06 UTC, carmeltsadok commented on GetQuestionnaireSchemas/index.ts
> +        }
I know. but I think that maybe we should require it for at least some of the roles (let's discuss it).

2021-06-01 07:07 UTC, carmeltsadok commented on GetQuestionnaireSchemas/index.ts
> +
We can return an empty array.

2021-06-10 08:41 UTC, lustigy96 approved these changes

2021-06-10 08:41 UTC, merged