Reports api
alphayesodot/itur-be-functionapp pull request #60
Opened 2021-06-02 14:50 UTC by maykremer

2021-06-02 16:00 UTC, carmeltsadok requested changes

2021-06-02 16:00 UTC, carmeltsadok commented on GetReports/index.ts
> +            user.role !== Role.Technical
Change if not includes in array of roles

2021-06-02 16:00 UTC, carmeltsadok commented on GetReports/index.ts
> +        if (events.length < 1) {
```suggestion
        if (!events.length) {

```

2021-06-07 06:35 UTC, lustigy96 requested changes

2021-06-07 06:35 UTC, lustigy96 commented on GetReports/function.json
> +    },
```suggestion
      "route": "reports"
    },
```

2021-06-07 06:35 UTC, lustigy96 commented on GetReports/index.ts
> +            status: 202,
303 status code is 'accepted' It is irrelevant to a get function
```suggestion

```

2021-06-07 06:35 UTC, lustigy96 commented on GetReports/config.ts
> +export default {
Where is the characterization?

2021-06-07 07:13 UTC, carmeltsadok approved these changes

2021-06-07 07:44 UTC, lustigy96 approved these changes

2021-06-07 08:19 UTC, carmeltsadok approved these changes

2021-06-07 08:19 UTC, merged