Event creator
alphayesodot/itur-be-functionapp pull request #61
Opened 2021-06-06 09:35 UTC by maykremer

2021-06-07 07:06 UTC, carmeltsadok requested changes

2021-06-07 07:06 UTC, carmeltsadok commented on CreateEvent/readme.md
> +# Event Queue Triggeer
Not sure it is needed. There are a lot of outdated interfaces

2021-06-07 07:06 UTC, carmeltsadok commented on shared/event/event.model.ts
> +            id: {
needs to check with vitaly

2021-06-07 07:12 UTC, carmeltsadok commented on CreateEvent/index.ts
> +        if (error) throw new Error(error.message);
Change to 
`const validationError: ValidationError = getReportsSchema.validate(req).error;        if (validationError) {            throw new ValidationFunctionError(functionName, validationError.message);        }`

2021-06-07 08:03 UTC, carmeltsadok approved these changes

2021-06-08 07:46 UTC, lustigy96 requested changes

2021-06-08 07:46 UTC, lustigy96 commented on CreateEvent/index.ts
> +
I think that if we suppose a good input, so this check is unneeded.. 
and if we don't, so it's better to check that myQueueItem is a JSON object, and not just ensure that it is not a string.

2021-06-09 12:08 UTC, lustigy96 approved these changes

2021-06-10 08:01 UTC, merged