GenerateConferenceUrl Function
alphayesodot/itur-be-functionapp pull request #68
Opened 2021-06-22 16:00 UTC by AdarPascal

2021-06-23 14:46 UTC, maykremer commented on GenerateConferenceUrl/index.ts
> +        await eventModel.updateOne({ _id: event._id }, { url: interviewUrl });
change to findByIdAndUpdate()

2021-06-23 14:51 UTC, carmeltsadok requested changes

2021-06-23 14:51 UTC, carmeltsadok commented on GenerateConferenceUrl/index.ts
> +const videoConferenceUrl: string = env.get('VIDEO_CONFERENCE_URL').required().asUrlString();
Add to config file

2021-06-23 14:52 UTC, maykremer requested changes

2021-06-23 14:52 UTC, maykremer commented on GenerateConferenceUrl/index.ts
> +        await eventModel.updateOne({ _id: event._id }, { url: interviewUrl });
change to findByIdAndUpdate()

2021-06-27 10:00 UTC, maykremer approved these changes

2021-06-27 11:55 UTC, carmeltsadok approved these changes

2021-06-27 11:56 UTC, merged