Added sms creator and sms sender function apps
alphayesodot/itur-be-functionapp pull request #76
Opened 2021-07-07 17:20 UTC by vitaly-furman

2021-07-07 17:39 UTC, carmeltsadok requested changes

2021-07-07 17:39 UTC, carmeltsadok commented on SmsCreator/function.json
> +      "queueName": "sms-creator-queue",
change the queue name in `GenerateConferenceUrl` to `sms-creator-queue` as well.

2021-07-07 17:39 UTC, carmeltsadok commented on SmsCreator/index.ts
> +            sendTime: '',
why empty string and not undefined?

2021-07-07 17:39 UTC, carmeltsadok commented on SmsSender/function.json
> +      "from": "+972529263458",
get from config

2021-07-07 17:39 UTC, carmeltsadok commented on SmsSender/function.json
> +      "from": "+972529263458",
Verify if there is any way to send it from anonymous phone number (without having to write our numbers)

2021-07-07 17:39 UTC, carmeltsadok commented on SmsSender/index.ts
> +        await smsModel.updateOne({ target: smsObject.target }, { sendTime: new Date() });
move it after the `personalPhoneNumber` validation. (because maybe it wasn't sent)

2021-07-07 17:39 UTC, carmeltsadok commented on SmsSender/index.ts
> +        if (!malshab.personalPhoneNumber) throw new FunctionError(functionName, 'Malshab missing personalPhoneNumber');
change to validation error

2021-07-07 17:39 UTC, carmeltsadok commented on SmsSender/index.ts
> +            to: formatPhoneNumber('0522611936'), // TODO: in prod change to malshab.personalPhoneNumber
get from config file (using environment variable that we will change on prod)

2021-07-07 21:53 UTC, AdarPascal commented on SmsCreator/function.json
> +      "queueName": "sms-creator-queue",
```suggestion
      "queueName": "sms-queue",
```

2021-07-07 22:04 UTC, AdarPascal commented on shared/sms/sms.model.ts
> +
What are those blank line spaces are for?
Non Air-bnb style.
Medubar Be Hochmolog

2021-07-08 07:14 UTC, vitaly-furman commented on SmsSender/function.json
> +      "from": "+972529263458",
It's a phone number that was given by twilio

2021-07-08 07:18 UTC, vitaly-furman commented on SmsCreator/index.ts
> +            sendTime: '',
Look in the sms model the default value is undefined

2021-07-08 08:55 UTC, vitaly-furman commented on SmsCreator/function.json
> +      "queueName": "sms-creator-queue",
queueName should remain sms-creator-queue, changed the out queue name in GenerateConferenceUrl to sms-creator-queue.

2021-07-08 08:56 UTC, vitaly-furman commented on SmsCreator/index.ts
> +            sendTime: '',
removed the sendTime, it will be undefined by default.

2021-07-08 10:48 UTC, vitaly-furman commented on SmsSender/function.json
> +      "from": "+972529263458",
It's possible to change to Alphanumeric number, when we will know about the exact name to be sent from then will change accordingly.

2021-07-08 11:30 UTC, vitaly-furman commented on SmsSender/index.ts
> +            to: formatPhoneNumber('0522611936'), // TODO: in prod change to malshab.personalPhoneNumber
It's a dynamic variable, the phone number is per malshab, it should not come from enviroment variables.

2021-07-08 12:04 UTC, carmeltsadok approved these changes

2021-07-08 12:30 UTC, carmeltsadok approved these changes

2021-07-08 13:39 UTC, AdarPascal approved these changes

2021-07-08 13:41 UTC, merged