initiate project
alphayesodot/itur-be-functionapp pull request #8
Opened 2021-02-08 13:13 UTC by maykremer

2021-02-08 14:19 UTC, vitaly-furman requested changes

2021-02-08 14:19 UTC, vitaly-furman commented on package.json
> +    "cross-env": "^6.0.3",
I don't thing you use this, remove it.

2021-02-08 14:19 UTC, vitaly-furman commented on package.json
> +    "@typescript-eslint/parser": "2.31.0",
Move to devDependancies.

2021-02-08 14:19 UTC, vitaly-furman commented on package.json
> +    "tsc": "^1.20150623.0",
Unused, remove.

2021-02-08 15:20 UTC, vitaly-furman submitted a review, later dismissed

2021-02-10 13:08 UTC, yonatandt requested changes
What is this function purpose? It is not clear to me.
Does it create an Event object, can it update an event object?

2021-02-10 13:08 UTC, yonatandt commented on events-service/index.ts
> +            await EventModel.create(eventObject).catch((err) => {
So does this function just create an event? what about updating the event (like the Trello card says)?
@yubbi99

2021-02-10 13:08 UTC, yonatandt commented on events-service/nodesGroup.interface.ts
> +}
Shouldn't be in this function

2021-02-10 13:08 UTC, yonatandt commented on events-service/nodesGroup.model.ts
> +export default nodesGroupModel;
Shouldn't be in this function.

2021-02-10 13:08 UTC, yonatandt commented on events-service/readme.md
> +listen to events-queue
and do what?

2021-02-10 13:08 UTC, yonatandt commented on events-service/sample.dat
> +sample queue data
Either put a sample or remove it from git.

2021-02-10 13:08 UTC, yonatandt commented on events-service/utils/validate.ts
> +});
So are all of these fields required in each message?

2021-02-10 13:08 UTC, yonatandt commented on events-service/utils/validate.ts
> +    status: Joi.string().required().valid(Status.Status1, Status.Status2), // TODO: insert statuses
So maybe you shouldn't put it here.
Note that right now, an object will not be valid if the status is not `Status1` or `Status2`.

2021-02-11 20:57 UTC, maykremer commented
> What is this function purpose? It is not clear to me.
> Does it create an Event object, can it update an event object?

Just create. Events API update events.

2021-02-11 21:04 UTC, maykremer commented on events-service/index.ts
> +            await EventModel.create(eventObject).catch((err) => {
Events api update events

2021-02-11 21:08 UTC, maykremer commented on events-service/nodesGroup.interface.ts
> +}
I need it in order to get the interviewer's array

2021-02-11 21:09 UTC, maykremer commented on events-service/nodesGroup.model.ts
> +export default nodesGroupModel;
I need it in order to get the interviewer's array

2021-02-11 21:11 UTC, maykremer commented on events-service/utils/validate.ts
> +});
yes.

2021-02-17 09:52 UTC, carmeltsadok requested changes

2021-02-17 09:52 UTC, carmeltsadok commented on events-service/index.ts
> +                });
I think you should check if the interviewer already exists in the array so there won't be repeated ids.

2021-02-17 09:52 UTC, carmeltsadok commented on events-service/index.ts
> +                if (!node.interviewers) throw new ApplicationError('There is no interviewers');
interviewers is a required field in nodesGroup, so why it won't exist?

2021-02-17 09:52 UTC, carmeltsadok commented on events-service/index.ts
> +            nodesGroups.forEach((node) => {
```suggestion
            nodesGroups.forEach((nodesGroup) => {

```

2021-02-17 09:52 UTC, carmeltsadok commented on events-service/function.json
> +  "scriptFile": "../dist/events-service/index.js"
```suggestion
  "scriptFile": "../dist/CreateEvent/index.js"
```
I think it should have a meaningful name and according to the naming conventions.

2021-02-17 09:52 UTC, carmeltsadok commented on events-service/index.ts
> +const createEvent: AzureFunction = async (context: Context, myQueueItem: IEvent): Promise<void> => {
Give a meaningful name to the queueItem.

2021-06-06 09:31 UTC, closed without merging