GetPreparationKitFiles Function
alphayesodot/itur-be-functionapp pull request #86
Opened 2021-07-13 10:16 UTC by PCOffline

2021-07-13 15:23 UTC, carmeltsadok requested changes

2021-07-13 15:23 UTC, carmeltsadok commented on config.ts
> +        preparationKitBlobName: 'preparation-kit',
Get from env

2021-07-13 15:23 UTC, carmeltsadok commented on GetPreparationKitFiles/index.ts
> +const GetPreparationKitFiles: AzureFunction = async (context: Context, req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```suggestion
const GetPreparationKitFiles: AzureFunction = async (context: Context, _req: HttpRequest, user: User): Promise<HttpTriggerResult> => {
```

2021-07-14 08:27 UTC, PCOffline commented on config.ts
> +        preparationKitBlobName: 'preparation-kit',
According to Adar, we set a convention that such strings can be hard-coded

2021-07-15 07:29 UTC, carmeltsadok commented on config.ts
> +        preparationKitBlobName: 'preparation-kit',
this config file gets the variables from the env.. I think you should add it with a default value (like other blob names in this file)

2021-07-15 11:54 UTC, carmeltsadok approved these changes

2021-07-19 07:18 UTC, lustigy96 approved these changes

2021-07-19 07:22 UTC, merged